### ISSUE TITLE
bootstrap repo by importing Clear Containers packaging scripts

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#1]
Now that Kata can be [built and run](https://github.com/kata-containers/documentation/wiki/Developer-Guide) we need to start thinking about building packages.

It probably makes sense to import https://github.com/clearcontainers/packaging with adjustments for Kata.

For the time being, we should also consider how best to deal with having two different runtimes. I suspect a virtual `kata-runtime` package would make sense which can depend on either `kata-runtime-cc` or `kata-runtime-runv`.

**Comment by jodh-intel** [comment]
@jcvenegas, @grahamwhaley, @egernst, @bergwolf - are we happy to close this now?

**Comment by grahamwhaley** [comment]
It would seem we have done that import and are actively using OBS, yes. +1 for closing from me @jodh-intel
