### ISSUE TITLE
Add support for aarch64 static images, multi-arch container

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#1000]
**Which feature do you think can be improved?**

kata-deploy only supports x86_64 today.

**How can it be improved?**

Support other awesome architectures, like aarch64.

**Additional Information**

Containers have support for multi-arch, and it'd be good if kata deploy leveraged this. We'll need to:

1) Add support for building static aarch64 images
2) Add support for building a multi-arch container image for kata-deploy.

**Comment by egernst** [comment]
There are a couple of other open issues with respect to aarch64 enabling.  While not useful for others, I'm wondering if it'd be feasible to create a project / Kanban to help track ARM specific issues.

**Comment by Pennyzct** [comment]
Hi~ @egernst
thanks for the raising~~~ We indeed really need to working more on kata deploy on aarch64. 
Agreed with you to create a project / Kanban to help track ARM specific issues. Some issues are stale and we already got the work done. ;)
