### ISSUE TITLE
fragements: disable some common kernel fragments

### ISSUE THREAD

**Issue by alicefr** [kata-containers/packaging#1010]
**Is your feature request related to a problem? Please describe.**

I need to disable a couple of config in `common` for s390x. For example `serial.conf`. I'd like to avoid to remove this confgs from the common

**Describe the solution you'd like**

Adding an additional file like `skip_config` and avoid to read the config fragment present in this list. This should be arch-specific

**Additional context**

Requirements to add s390x kernel fragments.

Any ideas or thoughts how to do that?

**Comment by grahamwhaley** [comment]
Hi @alicefr Right now, as you've probably figured out, we have no way to do that. So far we've been breaking fragments out into each specific arch (yes, copying them) if there are any arch's that don't need them.
I don't think there is a native fragment tooling way to 'exclude' : https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/kconfig/merge_config.sh

I could suggest we may add an optional go-lang-ish first line architecture identifier line, something like:

```
# arch: !s390x
```

that our scripts could look for - they could grep/head out that line if it exists, and if so, then parse it and take the appropriate action... just one thought.
/cc @Pennyzct who was just doing fragments I think?

**Comment by alicefr** [comment]
hi @grahamwhaley yes the header might be nicer than an additional file

**Comment by alicefr** [comment]
hi @grahamwhaley unfortunately we need a way how to disable an entire file and a single option in a file.

**Comment by alicefr** [comment]
or I have to those configs that conflicts with s390x from common to each arch. It might cause some duplications

**Comment by grahamwhaley** [comment]
Hi @alicefr Right. It might just be easier to pull the items out into the arch specific files then. Notionally common only has fully common items in it, so pulling some out and duplicating across the arch's that need them is not 'wrong'. We just have to keep an eye on it and decide if we are getting too fragmented and come up with a more complex scheme. I think right now, pull the fragments out and spread across the relevant arch files, and we can see what it looks like, but I think it will be fine.
