### ISSUE TITLE
stable-1.10: remove yq flag -X

### ISSUE THREAD

**Issue by chavafg** [kata-containers/packaging#1011]
# Description of problem

As stable-1.10 branch uses old version of yq which does not support that flag

**Comment by wainersm** [comment]
@chavafg hello,

Also on master branch there is a conflict on yq versions installed by osbuider (2.4.0) and required by packaging (3.1.0) which end up on this -X failing message when I try to build a custom kernel.

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
