### ISSUE TITLE
Consider adding libselinux as a dependency in OBS packages 

### ISSUE THREAD

**Issue by amshinde** [kata-containers/packaging#1018]
For distributions that support selinux like Fedora and Centos, we should consider adding libselinux as a build dependency, since the runtime depends on this for supporting selinux.

**Comment by amshinde** [comment]
cc @jodh-intel @jcvenegas @GabyCT

**Comment by jodh-intel** [comment]
+1. Now that https://github.com/kata-containers/runtime/pull/2624 has landed, we can build with `make FEATURE_SELINUX=yes` and depend on `libselinux`, but we'll need conditional logic in the RPM templates so we do **not** do this for SUSE systems (which use apparmor by default).

**Comment by amshinde** [comment]
@jodh-intel I am going to close this, as it was decided not to continue with OBS packaging going forward.
