### ISSUE TITLE
stable-1.10: repos missing in update-repository-version.sh and tag_repos.sh scripts

### ISSUE THREAD

**Issue by chavafg** [kata-containers/packaging#1028]
# Description of problem

`documentation` and `kata-containers` repos need to be added to:
1. https://github.com/kata-containers/packaging/blob/stable-1.10/release/update-repository-version.sh#L166-L175
2. https://github.com/kata-containers/packaging/blob/stable-1.10/release/tag_repos.sh#L70-L79

**Comment by GabyCT** [comment]
Closing this issue as it has been solved
