### ISSUE TITLE
pkgs: Enable ubuntu 20.04 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#1080]
**Which feature do you think can be improved?**

Enable ubuntu 20.04

**How can it be improved?**
1. Send a PR to modify the following file:
https://github.com/kata-containers/packaging/blob/master/obs-packaging/distros_x86_64
The change should include 
```diff
+xUbuntu_20.04::Ubuntu:20.04::universe
```
2. Run the packaging CI to verify it builds 
`/AzurePipelines run`
3. Even if passed the CI, verify that the packages were created successfully
https://build.opensuse.org/project/show/home:katacontainers:ci:x86_64:packaging-PR-<YOUR_PR_NUMBER>
4. The CI for packaging only tries to  validate if the build was successful, verify in a ubuntu 20.04 system, if it is working 
```bash
$ ARCH=$(arch)
$ YOUR_PR_NUMBER="<INSERT-PR-NUMER-HERE>"
$ sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:katacontainers:ci:x86_64:packaging-PR-${YOUR_PR_NUMBER}/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
$ curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
$ sudo -E apt-get update
$ sudo -E apt-get -y install kata-runtime kata-proxy kata-shim
```

5. All ready to merge  :) 

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by jodh-intel** [comment]
Hi @jcvenegas - I'm perfectly happy for us to add support for 20.04, but what about all the other recent distro versions on https://github.com/kata-containers/kata-containers/issues/198 (F32, CentOS 8, etc) ?

/cc @devimc, @chavafg.

**Comment by jcvenegas** [comment]
@jodh-intel, hey agree, we are getting a new generation of LTS distros probably will want to make an effort to upgrade our systems and supported distros.  Just as additional comments, I feel that has a bit more value to enable as a user request, if not could be a bit of overhead to keep the eye on all the distros. About Fedora I think we agreed ( need to find where) that for users should use the distro packages (that is great for us, less maintenance on the packaging side and more folks using will help to improve the integration on Fedora).

**Comment by jcvenegas** [comment]
I general I would like to see more an more users use snaps for ubuntu or kata deploy for general usage of Kata. Ensure that we can build for a distro will give value until distros try to add kata and face some issues that need to be solved based in their packaging policy (like in fedora that caused come to interesting ideas like use dracut rootfs, host kernel and initrd).
