### ISSUE TITLE
Stop building community packages for distros which maintain their own packages

### ISSUE THREAD

**Issue by fidencio** [kata-containers/packaging#1119]
This issue is related to: https://github.com/kata-containers/documentation/issues/708

Seems that we can stop building, right now, packages for:
- [x] CentOS
- [x] Fedora
- [x] openSUSE
- [x] RHEL
- [x] SLE

The only thing needed is the confirmation from openSUSE / SLE folks and an update in the documentation.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/documentation/issues/708.
