### ISSUE TITLE
Shall we get rid of 2.0-dev branch?

### ISSUE THREAD

**Issue by fidencio** [kata-containers/packaging#1161]
My understanding is that the 2.0-dev branch may have been used before creating / syncing https://github.com/kata-containers/kata-containers/tree/2.0-dev/tools/packaging.  Right now, its existence may be confusing (at least it's for me).

Shall we get rid of the branch entirely?

**Comment by jodh-intel** [comment]
It sounds good to me, but I don't know who created the branch originally.

@jcvenegas - do you know the history?

**Comment by jcvenegas** [comment]
I agree, now this is more valid as we have move to main naming

**Comment by jcvenegas** [comment]
Branch removed
