### ISSUE TITLE
ppc64le: Get public repos available via OBS. 

### ISSUE THREAD

**Issue by nitkon** [kata-containers/packaging#118]
Public repos from OBS for CentOS, Fedora, Red Hat and Ubuntu for x86 are available [here](https://github.com/kata-containers/documentation/blob/master/install/README.md#distros)

Make the same available for ppc64le as well. 
OBS support for ppc64le is availble: https://build.opensuse.org/monitor

More info in this comment: https://github.com/kata-containers/packaging/pull/102#issuecomment-408021025

**Comment by nitkon** [comment]
@erick0z @jcvenegas: Is there anything on the OBS side, like a check-box or something that needs to be ticked to run OBS builds on ppc64le and then see what breaks?

**Comment by jodh-intel** [comment]
Hi @nitkon - I think I answered that question here if you read it carefully: https://github.com/kata-containers/packaging/pull/102#issuecomment-408021025

**Comment by nitkon** [comment]
```
#...../packaging/obs-packaging# osc co home:katacontainers:release
Server returned an error: HTTP Error 401: Unauthorized
```

**Comment by nitkon** [comment]
I have added `ppc64le` in the <arch></arch> tag. 
```
#......../packaging/obs-packaging/home:katacontainers:release# osc meta prj -e
Sending meta data...
BuildService API error: change_project_no_permission (403)
no permission to change project
Try again? ([y/N]): y
Sending meta data...
BuildService API error: change_project_no_permission (403)
no permission to change project
Try again? ([y/N]): 
```

**Comment by jodh-intel** [comment]
Hi @nitkon - what's your obs user called?

Hi @jcvenegas - please could you add @nitkon to the OBS project once we know his username?

**Comment by nitkon** [comment]
Hi @jodh-intel , my obs user is called "nitkon" 
```
osc whois
nitkon: "Nitesh Konkar" <xxx@gmail.com>
```

**Comment by nitkon** [comment]
@jcvenegas , ping!

**Comment by nitkon** [comment]
@jodh-intel : Is there anyone else who can add me to the OBS project?

**Comment by jodh-intel** [comment]
Hi @nitkon - I think if you "request role addition" on this page, it will get routed to the right person:

- https://build.opensuse.org/project/show/home:katacontainers:release

**Comment by nitkon** [comment]
@jodh-intel : Done! Thanks.

**Comment by nitkon** [comment]
@jcvenegas : I have requested addition on the page mentioned by @jodh-intel , Can you please do the needful if you have the apt rights to do it.

**Comment by nitkon** [comment]
Request 627825 (new) still in new state, who is the right person to contact? 
Created the request here: https://build.opensuse.org/project/show/home:katacontainers:release

**Comment by jcvenegas** [comment]
@nitkon hey sorry my mail is missing some notifications.  I will add you today.

Meanwhile, somethink I dont  like but we do in the OBS repos is that when build kata  we upload a golang tarball to ensure we use the same golang version in all the distros. But the golang version is for x86_64 so adding more architectures to build will requeire to upload more tarballs or remove that tarball depedency..

In order to upload the rigth golang version I was thinking to create multiple github subprojects. Like:

https://build.opensuse.org/project/show/home:katacontainers:releases:x86_64:1.2.0

Does it make sense or you prefer to upload all the golang tarballs to the same project and at build time what tarball install? Or remove that tarball dependency.

**Comment by jcvenegas** [comment]
So for initial work I grant you access to our "testing repo"

https://build.opensuse.org/project/show/home:katacontainers:alpha

Feel free to upload and modify all you want here, there is not problem if you break the build.

After we are ready we can move to release.

**Comment by nitkon** [comment]
Hi @jcvenegas ,
I am ok with having a separate repository for ppc64le, something like https://build.opensuse.org/project/show/home:katacontainers:releases:ppc64le:1.2.0 I can place a ppc64le go tarball for that repo.

**Comment by nitkon** [comment]
Update on latest status on building packages in OBS for ppc64le is as follows: 

1. kata-containers/packaging/obs-packaging# ARCH=ppc64le bash -x ./create-repo-branch.sh 1.7.0-rc1
2.  kata-containers/packaging/obs-packaging# PUSH=1 OBS_SUBPROJECT="alpha:ppc64le:1.7.0-rc1" bash -x ./build_from_docker.sh 1.7.0-rc1

```

======= Updating runtime =======
/usr/local/go/bin/go
INFO: requires:
INFO: proxy 1.7.0~rc1+git.c5c4bc3-2
INFO: shim 1.7.0~rc1+git.d2c94a0-2
INFO: kata-linux-container 4.19.28.22-2
INFO: ksm-throttler 1.7.0~rc1+git.11b4625-2
INFO: image 1.7.0~rc1-2
Server returned an error: HTTP Error 404: Not Found
Error getting meta for project 'home%3Akatacontainers%3Aalpha%3Appc64le%3A1.7.0-rc1' package 'qemu-lite'
home:katacontainers:alpha:ppc64le:1.7.0-rc1/qemu-lite
ERROR: failed to checkout:makeurl: https://api.opensuse.org ['source', 'home%3Akatacontainers%3Aalpha%3Appc64le%3A1.7.0-rc1', 'qemu-lite', '_meta'] {}
root@kata1:/home/nitesh/split_patch/src/github.com/kata-containers/packaging/obs-packaging# grep -irwn "qemu-lite" *
```

Results: https://build.opensuse.org/project/show/home:katacontainers:alpha:ppc64le:1.7.0-rc1 

cc @jcvenegas @jodh-intel

**Comment by marcov** [comment]
hi @nitkon 
- the first error with the runtime, looks like it is expecting to find a `qemu-lite` package in your OBS project. You need to figure out who and why it is doing it.

- linux-container fail it's because the [config files tarball you uploaded](https://build.opensuse.org/source/home:katacontainers:alpha:ppc64le:1.7.0-rc1/linux-container/kata-kernel-configs.tar.gz?rev=27c7c50688f191237e52aa0810dc5587) on OBS is incomplete.
Make sure your `packaging/kernel/configs` contains a `powerpc_kata_kvm_4.19.x` file.

**Comment by nitkon** [comment]
Hello @marcov ,
1. The [qemu-lite](https://github.com/kata-containers/packaging/blob/6a53aeca27bf95c00a10962ed14bd8ce05acdb06/obs-packaging/runtime/update.sh#L64) requirement should be made optional for other archs as it would be a necessity only for x86?

2. linux-container build was failing as I was on older branch. [This](https://build.opensuse.org/project/show/home:katacontainers:alpha:ppc64le:1.7.0-rc1) is the latest status. 

3. Since the builds on some of the distros are green, what would be the steps from here on to make it a part of the kata release cycle? @jcvenegas 

4. Is there anyway to make sure that all the other distros like Ubuntu 1604/1804, RHEL 7 instances are always available in OBS for non-x86 archs? Currently `unresolvable` means those instances are not available in OBS.

Thanks!

**Comment by marcov** [comment]
> 1. The [qemu-lite](https://github.com/kata-containers/packaging/blob/6a53aeca27bf95c00a10962ed14bd8ce05acdb06/obs-packaging/runtime/update.sh#L64) requirement should be made optional for other archs as it would be a necessity only for x86?

I let @jcvenegas clarify on this

> 4. Is there anyway to make sure that all the other distros like Ubuntu 1604/1804, RHEL 7 instances are always available in OBS for non-x86 archs? Currently `unresolvable` means those instances are not available in OBS.

You need to make sure the repositories you are building for supports your architecture. E.g. for Ubuntu 18.04 you should use https://build.opensuse.org/project/show/Ubuntu:18.04:Ports

**Comment by nitkon** [comment]
@marcov : Thnx. [updated](https://build.opensuse.org/project/show/home:katacontainers:alpha:ppc64le:1.7.0-rc1). Nit: As of today RHEL_7 on ppc64le is not available in OBS.
