### ISSUE TITLE
.ci/lib.sh: install_yq fails on ppc64le

### ISSUE THREAD

**Issue by nitkon** [kata-containers/packaging#124]
install_yq() has no arch entry for ppc64le and hence installing yq fails on IBM Power systems.

Terminal Output:
/root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: 1: /root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: Not: not found
/root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: 1: /root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: Not: not found
/root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: 1: /root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: Not: not found
/root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: 1: /root/nitesh/split_patch/src/github.com/nitkon/packaging/yq: Not: not found

:~src/github.com/nitkon/packaging# cat yq
Not Found

**Comment by jodh-intel** [comment]
Hi @nitkon - it would be helpful (both here and in future) if you could put more detail into issues (error messages, log extracts, etc) so that we can all understand a bit more about them :)
