### ISSUE TITLE
vhost-vsock needs to be loaded first for it to be used. Handle this in our packaging.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/packaging#137]

**Comment by amshinde** [comment]
cc @jcvenegas

**Comment by ydjainopensource** [comment]
I dont know if this is related,  but just for the reference, Z does not support vhost-vsock-pci so you will have to load vhost-vsock-ccw instead

**Comment by jodh-intel** [comment]
@ydjainopensource - on the topic of Z and packaging, you may need to raise a PR to make changes to our qemu configuration script for zSeries:

- https://github.com/kata-containers/packaging/blob/master/scripts/configure-hypervisor.sh.
