### ISSUE TITLE
Fix golang version used for OBS

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#147]
From https://github.com/kata-containers/packaging/blob/master/obs-packaging/gen_versions_txt.sh#L46..L47:

```
golang_version=$(get_from_kata_deps "languages.golang.meta.newest-version" "${kata_version}")
golang_version="1.10.2"
```

That doesn't look correct as we're resetting the value read from https://github.com/kata-containers/runtime/blob/master/versions.yaml.

I think the fix is to:

- Delete the `golang_version="1.10.2"` line.
- Update https://github.com/kata-containers/runtime/blob/master/versions.yaml to specify `languages.golang.meta.newest-version=1.10.2` (or even `1.10.3` now - see https://golang.org/dl/ ?)

Related: https://github.com/kata-containers/runtime/pull/643.

**Comment by jodh-intel** [comment]
Actually, that's not quite right. I think we need to do this:

- Delete the `golang_version="1.10.2"` line.
- Change that file to query `languages.golang.version` from `versions.yaml`.
- Update https://github.com/kata-containers/runtime/blob/master/versions.yaml to specify `languages.golang.version=1.10.2` (or even `1.10.3` now - see https://golang.org/dl/ ?)

**Comment by jodh-intel** [comment]
`languages.golang.meta.newest-version` was originally envisioned only for testing purposes: we'd run tests using `languages.golang.meta.newest-version` and if they all passed, we'd set:

```
languages.golang.version = languages.golang.meta.newest-version
```

Then, when new versions of golang were released, we'd update `languages.golang.meta.newest-version`.

**Comment by jodh-intel** [comment]
I see that we're also querying the golang version in `Makefile` so maybe this script could be changed to use `GO_VERSION` so we only query once?

**Comment by jodh-intel** [comment]
@jcvenegas - is this fixed now?

**Comment by jcvenegas** [comment]
@jodh-intel I think so now we create the versions.txt file based on versions.yaml so we will use the version suggested by a release.
