### ISSUE TITLE
Add scripts to automate packing process for kata-containers 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#15]
Add scripts to build packages to be build with OBS. Add support to build and package the following:

- runtime
- proxy
- shim
- agent(inside an guest os)
- linux kernel
- qemu lite

The packaging tools need support for local build and publish a build on OBS servers.

The packages tools could be build to point to a github  commit or a tag.

**Comment by erick0z** [comment]
Also:
- qemu-lite (https://github.com/kata-containers/qemu/tree/qemu-lite-2.11.0)

**Comment by erick0z** [comment]
@jcvenegas @egernst @GabyCT @chavafg @jodh-intel The Kata-containers packages for tag 0.0.1 are ready to be tested. They can be found here (https://build.opensuse.org/project/show/home:katacontainers:alpha). I just ran a quick test on a fedora 27 system and works as expected. Right now, the packages works for Fedora 27, Ubuntu Xenial and CentOS 7 (Except qemu-lite).

**Comment by jcvenegas** [comment]
@erick0z  thanks, @GabyCT  @jodh-intel  @grahamwhaley @egernst  @chavafg  we need to start to add docs to install at least in ubuntu  fedora and centos. 

I can pick ubuntu

**Comment by jcvenegas** [comment]
Update please use https://build.opensuse.org/project/show/home:katacontainers:release to test in your system.
