### ISSUE TITLE
kernel: support block IO weights

### ISSUE THREAD

**Issue by devimc** [kata-containers/packaging#156]
we need `CONFIG_CFQ_GROUP_IOSCHED` to support block IO weights  (docker `--blkio-weight` and `--blkio-weight-device`)

see https://www.kernel.org/doc/Documentation/cgroup-v1/blkio-controller.txt

**Comment by grahamwhaley** [comment]
Where do we think this blockio weighting is going to happen?
If in the guest, is this intended to work for pods then? I suspect for individual containers (single docker container for instance), the effect may ultimately be benign (weighting a single container gives it 100% I think).
If on the host, then I'm not sure if this will get out across the VM boundary and into the host, and then even if it did, according to the [docker docs page](https://docs.docker.com/engine/reference/run/#block-io-bandwidth-blkio-constraint), it seems that:

> **Note:** The blkio weight setting is only available for direct IO. Buffered IO is not currently supported.

and right now, afaik, we map our block mounts on the host side cached, so the guest transfers will maybe not hit the host side in O_DIRECT mode anyway (maybe this week I'll get to raise the RFC PR so we can discuss if we should turn off host side caching...).

**Comment by devimc** [comment]
@grahamwhaley 
> If in the guest, is this intended to work for pods then?

yes, from my point of view each container in a pod can have a different blockIO weight, if we apply the constraint to QEMU we won't see that independence 

I think we need more input here

@mcastelino @amshinde @egernst  what do you think?

**Comment by devimc** [comment]
FYI this config is already set in PPC

**Comment by grahamwhaley** [comment]
@devimc thanks for the clarification. From my pov then:
- that sounds fine, presuming that pod orchestrators such as k8s can/do pass that info into the pod :-)
- that I suspect we are somewhat overdue trying to document where a feature behaves a little differently between a software container (runc), and a kata container - and I suspect this is one such case. On a soft container/pod I suspect the weightings apply across the whole host?, whereas for kata they apply inside the pod, and all pods are equal on the the host side.
I don't think we have anywhere we document things like that at present beyond the [limitations doc](https://github.com/kata-containers/documentation/blob/master/Limitations.md)
