### ISSUE TITLE
include versions.yaml in runtime package

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#165]
Our "versions database" is used heavily by various repos to determine which versions of external/3rd party components/tools/images to build/test/package with:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml

The file is well documented and -- being YAML -- actually human readable.

We should add this file to the `kata-runtime` package as:

```
/usr/share/doc/kata-containers/versions.yaml.gz
```

For bonus points, we could either update the `versions.yaml` file itself (via a runtime PR), or create a `/usr/share/doc/kata-containers/README` file explaining how to install a tool to query this database (such as https://github.com/mikefarah/yq), along with a few examples such as:

```

    # To determine the version of go used to build, test and package this release:
    ```
    $ yq read versions.yaml languages.golang.version
    ```

``` 

It will take up a tiny amount of space (~2k compressed) and will allow non-developers to determine how their system deviates from the test environment the packaged version of kata was built/tested/packaged using. This could be particularly useful for users choosing to use a stable (packaged) release.

/cc @egernst, @jcvenegas.

**Comment by jcvenegas** [comment]
would be great `kata-runtime kata-env --deps 'languages.golang.version'` provide the information to not depend in an external tool

**Comment by jodh-intel** [comment]
@jcvenegas - That is a good idea! We should add YAML support to the runtime but as we've already got JSON and TOML support, it may make sense to consider doing this...

- Switch the runtime to use https://github.com/spf13/viper for config handling (which is used by Jaeger fwiw)

- Add support for `--deps` using viper's `.Sub()` feature: https://github.com/spf13/viper#extract-sub-tree

- Add a `--json` option

- Potentially add a `--output-format=[toml,json,yaml]` which is cleaner than `--json` and `--yaml` imho.

Another random thought - `kata-check` and `kata-env` are extremely useful, but those commands are *only* ever run by users / admins. We might therefore want to look at how much of the overall runtime size those commands account for. If it's significant, we could make those commands plugins which are only loaded on demand.

**Comment by jodh-intel** [comment]
As the above is going to take a bit of effort, it might be best to just provide the raw YAML file for now - even if users are not able to obtain a tool like `yq`, they can just use the standard tools to view the file rather than querying it.

We might also want to think about adding the versions database from the tests repo too fwiw:

- https://github.com/kata-containers/tests/pull/701
