### ISSUE TITLE
kernel config: why CONFIG_IPV6_SIT=y?

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/packaging#171]
Currently each guest would always have a link/sit interface inside. Any reason we would always want that one? @devimc @sboeuf @WeiZhang555 @amshinde (not sure who to @, so just copying a few random ppl :).

**Comment by jodh-intel** [comment]
Leveraging https://github.com/kata-containers/community/wiki/Areas-of-interest....

/cc @jon, @amshinde, @mcastelino (aka "network god" :)

**Comment by devimc** [comment]
@bergwolf good find!, I think we don't need it

**Comment by jodh-intel** [comment]
Related: #8, #56.

**Comment by amshinde** [comment]
@bergwolf Nice find. No we dont need this.

**Comment by sboeuf** [comment]
@bergwolf please open a PR to remove this.

**Comment by WeiZhang555** [comment]
Yes, I agree we don't need it :-)
