### ISSUE TITLE
Kernel build setup issues

### ISSUE THREAD

**Issue by xzr** [kata-containers/packaging#178]
Greetings. I started looking into building a custom kernel for some testing purposes.

I cloned the packaging repo and followed instructions to run 'build-kernel.sh setup'.
I got the following error:
> ERROR: failed to find /home/xzr/go/src/github.com/kata-containers/packaging/kernel/patches//../kata_config_version 

I suspect the script expects some kind of directory structure to be in place for it to work properly. 

I managed to make it work by creating the directory structure in the error and placing the configs folder and kata_config_version in their respective places from the repo. I also modified the script a bit to download the kernel source.

I feel the documentation and possibly scripting could be improved regarding this.

**Comment by jodh-intel** [comment]
Thanks for raising @xzr!

Could you tal @jcvenegas?

**Comment by jcvenegas** [comment]
@xzr thanks for create the issue yes, the scripts expect the config and patches be in your gopath
so expect we download the repository doing `go get`, It make sense to find the patches in a relative directory to the script.

**Comment by xzr** [comment]
Thanks for the quick reply @jcvenegas !

It's not quite clear what to set the GOPATH variable to though. 

I reckon the most common use case for someone trying to rebuild the kernel is that they just clone the packaging repo and follow the instructions. Currently there's no mention about setting up the directory structure in a certain way.
