### ISSUE TITLE
kata-runtime installation dependency for qemu-*  is wrong

### ISSUE THREAD

**Issue by marcov** [kata-containers/packaging#193]
The installation dependencies for `kata-runtime` is not correctly set for RPM based distributions.

Because of this, an upgrade of the kata packages version results in not updating qemu-* packages.
These are the current dependencies for `kata-runtime`:
```
$ zypper info --requires kata-runtime                                                                                     
...
Requires       : [12]                                                                                                 
    libpthread.so.0()(64bit)
    libpthread.so.0(GLIBC_2.2.5)(64bit)
    libpthread.so.0(GLIBC_2.3.2)(64bit)
    libc.so.6(GLIBC_2.2.5)(64bit)
    /bin/bash
    kata-containers-image >= 1.3.0~rc1-34
    kata-ksm-throttler >= 1.3.0~rc1+git.48a9568-35
    kata-linux-container >= 4.14.67.11-137
    kata-proxy >= 1.3.0~rc1+git.981fef4-34
    kata-shim >= 1.3.0~rc1+git.9b2891c-35
    qemu-lite >= 2.11.0-50
    qemu-vanilla >= 2.11.2-4
```

When comparing the listed dependency with a former qemu-lite version:

```
$ zypper vcmp 2.11.0-50 2.11.0+git.a39e0b3e82-48.2.x86_64                                                  
2.11.0-50 is older than 2.11.0+git.a39e0b3e82-48.2.x86_6
```

This means than when upgrading to a new version of kata-runtime, qemu will not be upgraded.

This can potentially lead to errors such as: `Failed to check if grpc server is working: rpc error: code = DeadlineExceeded desc = context deadline exceeded`, as in kata-containers/runtime#702, kata-containers/runtime#516, kata-containers/runtime#576, kata-containers/runtime#626, ...

**Comment by jodh-intel** [comment]
Ouch! Good catch @marcov - feel free to assign yourself as well (or unassign @jcvenegas if you have the fix :)

**Comment by marcov** [comment]
@jodh-intel: I tried that but being a member of `kata-containers/packaging` is not enough to have admin rights on this repo.

**Comment by grahamwhaley** [comment]
Hi @marcov - I had a check up - yeah, you have admin rights on a few repos, and read on the rest.
I can see the summary at https://github.com/orgs/kata-containers/people/marcov - if you can see that.
I'll assign this to you. I guess the level of repo control for members might need more refining...

**Comment by marcov** [comment]
@grahamwhaley thanks for checking. Lol that link is 404 for me :disappointed:
