### ISSUE TITLE
Pushing deb/spec files to OBS fails

### ISSUE THREAD

**Issue by nitkon** [kata-containers/packaging#199]
Command: PUSH=1 OBS_SUBPROJECT="alpha:ppc64le:1.3.0-rc1" bash -x ./build_from_docker.sh  1.3.0-rc1
```
+ ./update.sh -p 1.3.0-rc1
/usr/local/go/bin/go
Server returned an error: HTTP Error 404: Not Found
Error getting meta for project 'home%3Akatacontainers%3Aalpha%3Appc64le%3A1.3.0-rc1' package 'linux-container'
home:katacontainers:alpha:ppc64le:1.3.0-rc1/linux-container
ERROR: failed to checkout:makeurl: https://api.opensuse.org ['source', 'home%3Akatacontainers%3Aalpha%3Appc64le%3A1.3.0-rc1', 'linux-container', '_meta'] {}
```

**Comment by nitkon** [comment]
I think we are missing out on `linux-container` here https://github.com/kata-containers/packaging/blob/01b68b1ca65969db6406eeb74b5fc92ffbe33b2e/obs-packaging/scripts/obs-pkgs.sh#L12 .

**Comment by marcov** [comment]
Hi @nitkon, the problem seems to be with the `OBS_SUBPROJECT` value you used, it should be 
`alpha:ppc64le:1.3.0-rc1`
The package named kernel it's something legacy I think.

**Comment by nitkon** [comment]
Hi @marcov , yes I have used OBS_SUBPROJECT value as `alpha:ppc64le:1.3.0-rc1`

This is the command I have used, `Command: PUSH=1 OBS_SUBPROJECT="alpha:ppc64le:1.3.0-rc1" bash -x ./build_from_docker.sh 1.3.0-rc1`

I did not understand your diagnosis of the problem.

**Comment by marcov** [comment]
Hi @nitkon, I may have misread the command you used, I am sorry  :)
