### ISSUE TITLE
Handle migration from Clear Containers / runv to kata containers

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#2]
Once #1 is closed, we need to consider how to upgrade a system installed with either:

- [Clear Containers](https://github.com/clearcontainers/runtime/wiki/Installation)
- [runv](https://github.com/hyperhq/runv)

... and allow users to run the appropriate packaging command to upgrade to Kata.

For example, if Clear Containers is installed on an Ubuntu system, the following should install all required Kata components and remove the Clear Containers ones:

```
$ sudo apt-get install kata-runtime-cc
```

**Comment by egernst** [comment]
We're getting pretty close to parity with cc-runtime; I think we'll need this figured out at that point (aka, v. soon).

**Comment by jodh-intel** [comment]
This is effectively fixed by https://github.com/kata-containers/documentation/pull/79.

ftr, the upgrade logic outlined in the description above is a *bad idea* since:

- Installing a new software component should not silently uninstall a (different) set of components (it's surprising, which is bad :)
- Clear Container and Kata Containers can co-exist so it's strictly unnecessary for one to remove the other (although recommended since Kata is the future wrt development focus).

wdyt @egernst - can we close this one when we get enough acks on https://github.com/kata-containers/documentation/pull/79?
