### ISSUE TITLE
Link `release` repository to `master`

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#205]
Now that stable branches started to be generated and additional architectures will be supported.

The previous repository that was used to allow users install kata from packages is:
https://build.opensuse.org/project/show/home:katacontainers:release

But now a new URL format is used:
https://build.opensuse.org/project/show/home:katacontainers:releases:`ARCH`:`BRANCH`

Example:
https://build.opensuse.org/project/show/home:katacontainers:releases:x86_64:master

To allow current users of the old repository keep updating Kata, lets link this repository with `master` `x86_84` (release repository only provided x86_64).

From @marcov  suggestion 

> @jcvenegas it can probably be done with `aggregatepac`, that is basically used to just have a copy of the package artifacts from a project to another.
```
osc copypac home:katacontainers:release $(PKGNAME) home:katacontainers:releases:x86_64:master
osc rdelete home:katacontainers:release $(PKGNAME)
osc aggregatepac home:katacontainers:releases:x86_64:master $(PKGNAME) home:katacontainers:release
```

**Comment by jcvenegas** [comment]
I'll take care of this on weekend to reduce the  impact of users using this repo.

**Comment by marcov** [comment]
@jcvenegas nice! Let me know if you need help.
