### ISSUE TITLE
Find a way to build the image or initrd from source in packages

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#219]
To help linux distributions adoption the packages should be build from source.

The image in packaging scripts is generated first and then used as source file to build it.
We could try to find a way to create the image from source.

Some possible solutions are:
Kiwi suggested by @marcov 

As alternative:
1. build the agent 
2. copy files  for the guest rootfs from the host rootfs 
An approach like clr-init could be used:
https://github.com/clearlinux/clr-init/blob/master/Makefile#L4

That approach could be used as a new osbuilder target:
to do something like ... 
`make make-rootfs DISTRO=host`
```bash
arch=lib64
BINFILES=(/usr/bin/iptables ...)
mkdir -p rootfs/{sys,dev,proc,tmp,var,sysroot,usr/sbin,usr/bin,usr/lib/systemd/system-generators,usr/${arch},usr/${arch}/multipath,run,root}

for file in ${BINFILES}; 
do 
        cp -f $file initramfs/$file;
done
cp $(ldd ${BINFILES} | awk '{print $$3}' | grep "^/" | sort | uniq) rootfs/usr/${arch}/ 
```

Then when we create the image package:

```rpmspec
source0: osbuilder.tar.gz
BuildRequires: iptables
...

%build
make make-rootfs DISTRO=host
make make-image DISTRO=host
make make-initrd DISTRO=host


```

**Comment by jcvenegas** [comment]
@marcov @nitkon @jodh-intel @grahamwhaley

**Comment by jodh-intel** [comment]
Using the host FS is an interesting idea but that would only work in limited scenarios I think. A few thoughts:

- What if you want a rootfs that isn't the same as the host?
- Package build env is going to potentially limited in different ways to the roots that Kata needs
  (in other words, the package build environment may not have the packages installed that are needed by the rootfs)
- *etc*

fwics, kiwi is https://doc.opensuse.org/projects/kiwi/doc/. That sounds really interesting but apparently currently only supports rpm-based distros. We could of course start moving to kiwi for those distros and either wait or adopt an alternative for deb-based distros.

I'd be surprised if Kata was the only project with "packaging challenges" like this. Does anyone know of any others (ideally with points to how they solve these issues :) ?

A random thought: we could consider *not* packaging the image but instead packaging a new tool (`kata-ctl`) that could download images and/or kernels from known secure locations. There are advantages to such a scheme - users would have access to more frequently updated images/kernels than packaging would allow (unless maybe we could leverage the RPM spec magic of https://github.com/clearlinux/autospec :) However, there are the obvious set of issues:

- security
- re-inventing the wheel (or should that be re-inventing hub.docker.com?! :)

But building on this random thought - maybe we could package up a set of kernels + images *as docker images* and use the standard docker tooling to `docker pull` the latest. We'd then only need a way to extract those images to the standard locations to avoid having to package image+kernels "manually" :)

**Comment by jodh-intel** [comment]
See also:

- http://lists.katacontainers.io/pipermail/kata-dev/2018-October/000505.html

**Comment by marcov** [comment]
I like the distribution model proposed by @jodh-intel based on the concept of image pulling.
This would also help in distributing images with different security levels, a problem that has been discussed recently.

`kata-ctl` could be used to pull a specific image and to update `configuration.toml`.

An offspring of @jodh-intel and @jcvenegas propositions is already achievable with `docker export`; i.e. start a container, install the packages, and then export the rootfs.


Or if you dont want to rely on Docker, there are also standalone tools used to manipulate container images, as [skopeo](https://github.com/containers/skopeo) (to pull images) and [umoci](https://github.com/openSUSE/umoci) (can unpack images and modify them).

E.g.:
```
skopeo copy docker://opensuse:leap oci:opensuse:leap
sudo umoci unpack --image oci:opensuse:leap bundle
```
And you have the rootfs available in `bundle/rootfs`

**Comment by jcvenegas** [comment]
So for kata-ctl the idea would be just pull the rootfs and build the image and initrd in the host right?
- This would need to publish the rootfs that is the Base OS + agent + required binaries by the agent (iptables etc) ?
   This would need a documented way to do kata-ctl image update after each kata containers update

Also I think in that way we need a better way to handle the image compatibility and the runtime. In the past was still needed but the image was build and provided before the users needed to use kata. Now this logic will be part user side. If we want to go in this way we should ask in the ML and bring it to the Kata arch forum.

**Comment by jodh-intel** [comment]
@jcvenegas - all good points! I've added this as an agenda item for the next Architecture Committee meeting:

- https://etherpad.openstack.org/p/katacontainers-2018-architecture-committee-mtgs

**Comment by jcvenegas** [comment]
added comments to ML. 
To summarice we are using kiwi for OBS packages as it works for our OBS plans and helps to integrate kata in SUSE, for new Distros adoptions we may need to find a more generic approach (or specific to the adopter).
@lsm5 I added you to the ML thread. I'd like to get some feedback from you :) .
