### ISSUE TITLE
Include the kernel configuration in the kernel package

### ISSUE THREAD

**Issue by amshinde** [kata-containers/packaging#226]
It will be useful to include the kernel configuration file used for building the kernel to understand what features have been included while debugging.

cc @jcvenegas @jodh-intel

**Comment by marcov** [comment]
I agree that this is a nice addition.

An important use case is the ability for the final users to know what are the features included in the default kernel, to evaluate if that is adequate to their needs.

The config could be installed in the same directory where the kernel resides now, similarly to what is done by modern distros with `/boot/config-x.y.z`

For cross-reference, this complements what was proposed by @jodh-intel at #222.

**Comment by jodh-intel** [comment]
+1. Yes, I think this is complementary to #222 (I think we should do both).

By having the config available in `/usr/share/kata-containers/` users/admins could potentially also determine if their particular workload *would run* with that configuration **before** actually attempting to run it.

This is also sort of related to #165.

**Comment by jodh-intel** [comment]
For completeness, I guess I should point out that adding the config would duplicate what is already provided in the source rpm for example for the guest kernel (the `kata-linux-container` package). However, the compressed kernel config file is small and the usefulness of having it on a system without sources installed outweighs the cost associated in adding it to the package imho.

**Comment by jcvenegas** [comment]
I think is already installed https://github.com/kata-containers/packaging/blob/master/obs-packaging/linux-container/kata-linux-container.spec-template#L149

**Comment by marcov** [comment]
@jcvenegas yes that's what @jodh-intel said, but it is provided in debug only. So the goal is to move the file in the (non-debug) kata-linux-container package.
```
$ rpm -q --whatprovides /usr/share/kata-containers/config-4.14.67.12-10.1.container 
kata-linux-container-debug-4.14.67.12-10.1.x86_6
```
