### ISSUE TITLE
s390: kernel configs

### ISSUE THREAD

**Issue by alicefr** [kata-containers/packaging#246]
Hi, I played around with the kernel configs for s390. I obtain a kernel without modules with this combination:
```
$ cd linux
$ make defconfig kvmconfig localyesconfig
$ make -j 
$ du -h arch/s390/boot/bzImage
6.4M	arch/s390/boot/bzImage
```
The `defconfig` turns on the default configs, `kvmconfig` turns on some options like `CONFIG_9P_FS` and `localyesconfig` converts the mods to core. After with `make menuconfig` I also tried to turn off other options for example some filesystem like `Btrfs` or `fuse` or some other feature likes `USB support` or `Auditing support`. I manage to obtain a kernel of 3.4 MB. However, this operation requires always to manually turn off some options. I like the combination of  `defconfig`, `kvmconfig` and `localyesconfig` because it gives a standard and automatic way how to create kernel configs for almost each kernel version. My question is that good enough for standard configuration?

**Comment by grahamwhaley** [comment]
That's a good start @alicefr :-), and could be a good first version committed. In general we try to make the kernel as small as we can. @egernst is looking at using kconfig 'fragments' and some existing kernel scripts that can combine fragments into a whole config file so we can use something like 'allno' config and then the required minimal fragments to get to a (near) optimal kernel. That work is ongoing though - we might want to add your config method for s390 above to get it up and running, and then we can refine...

**Comment by jodh-intel** [comment]
Hi @alicefr - We are trying to find ways to improve / audit / document the kernel config for Kata, but as @grahamwhaley says, this is a good start.

See: #8, #55, #56, #222, #223.
