### ISSUE TITLE
Add Debian 9 (stable) to OBS

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#247]
Related:

- https://github.com/kata-containers/ci/issues/87
- https://github.com/kata-containers/documentation/pull/306

**Comment by marcov** [comment]
Things to do:
- [ ] Enable builds for Debian:9.0 on OBS.
- [ ] Test building for Debian locally with `osc build Debian_9.0`
- [ ] Investigate on failures. I see [dh-modaliases](https://github.com/MrMEEE/bumblebee-ppa/tree/master/maverick/dh-modaliases) being a build requirement for Ubuntu, and this package is not part of standard Debian repos. But I dont see why it is needed to build kata components to begin with.

**Comment by marcov** [comment]
Lack of dh-modaliases is affecting these packages:
- ksm-throttler	
- proxy	
- runtime	
- shim	
If we get rid of this Build Requires, we should have Kata building for Debian.

**Comment by marcov** [comment]
So now that #250 is merged, we need to make these updates update available on OBS.

I am not sure what's the best way to do it:
- repeat the 1.4.0 release process for the components not building (see previous comment)
- Directly update the debian control / dsc files on OBS.
- Just wait for the next release

Thoughts @jcvenegas, @jodh-intel ?

**Comment by marcov** [comment]
> I'd rather we do this as cleanly as possible so although I'd love to see Debian OBS packages available asap, I don't think there is any burning urgency so I'd vote for:
> 
> > * Just wait for the next release

+1

> But having said that, we have for example:
> 
> * https://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/
> 
> I'm not clear on how this is being used right now, 

At the moment this contains the latest released version of kata, e.g. 1.4.0 as of today.

> but can't we run a periodic (weekly?) `master` build for scenarios like this? 

I think this is a good idea, and having nightly OBS builds was something already mentioned by @egernst.

We have most of the automation in place to push new packages to OBS, we'd basically just need a machine to run this. The trigger could be a cron job, or even better on demand whenever a change in one of the repos is detected.

/cc @jcvenegas

**Comment by jcvenegas** [comment]
I was talking with @chavafg  in the past to add a jenkins pipeline, not sure if there is any issue related with store some obs keys our kata jenkins ?

In that way that could be triggered not only weekly but if is needed a urgent build.

**Comment by jcvenegas** [comment]
@marcov do you know if there is an existing obs + jenkins integration today?

**Comment by grahamwhaley** [comment]
I had to have a surf, as I was curious. dunno if this will help or not:
https://github.com/openSUSE/snapper/wiki/Continuous-Integration-and-the-Open-Build-Service

**Comment by marcov** [comment]
I'm not aware of any plugins integrating OBS in Jenkins, but many people are using it to do CD on OBS so I can ask how do they deal with credentials.

**Comment by jodh-intel** [comment]
Any further updates on this? Would be good to keep the momentum going so we can get https://github.com/kata-containers/documentation/pull/306 landed "real soon now" (TM) :)

**Comment by marcov** [comment]
Debian 9.0 repositories are enabled, but some packages are not building as explained earlier.
This is repository URL to advance with the docs: https://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/Debian_9.0/

**Comment by GabyCT** [comment]
Closing this issue as we already have OBS packages for debian
