### ISSUE TITLE
Enable Fedora 29 repo on OBS 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/packaging#261]
Once Fedora 29 is available on OBS, we should enable them for our kata packages

**Comment by xasx** [comment]
Any change here? OBS eventually consistent?

**Comment by marcov** [comment]
> I tried to enabled from OBS web page, I dont see them as part of the current repositories.
> 
> Probably still needs time to propagate ?

@jcvenegas probably the GUI still need to catch up. The target repositories are stored in a XML config that you can edit with either:
- `osc meta -e prj`
or 
- From the project page, Advaced -> Meta (e.g. [this page](https://build.opensuse.org/project/meta/home:katacontainers:releases:x86_64tth:master))

For Fedora 29, as shown [here](https://build.opensuse.org/project/meta/Fedora:29), the project name is `Fedora:29`  and the associated repositories are `standard` and `update`.

**Comment by marcov** [comment]
I've added to the config `Fedora:29 standard`, let's see if it builds.

**Comment by jcvenegas** [comment]
All the builds are successful now.

**Comment by xasx** [comment]
Upon installing, I encounter

```
 Problem: conflicting requests
  - nothing provides qemu-lite >= 2.11.0+git.f886228-13 needed by kata-runtime-1.4.0+git.21f0059-15.1.x86_64
  - nothing provides qemu-vanilla >= 2.11.2+git.0982a56-13 needed by kata-runtime-1.4.0+git.21f0059-15.1.x86_64
```

Any chance to get these canonically?

**Comment by marcov** [comment]
@xasx  you will need to wait for the next release, both of them are not official distribution packages. 

Moving forward I think the generic qemu provided by the distro should be put as the only requirement.
