### ISSUE TITLE
OBS packages: fail to build with ubuntu 16.04

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#264]
Recently the ubuntu builds started to fail.

https://build.opensuse.org/project/monitor/home:katacontainers:alpha?arch_x86_64=1&defaults=0&failed=1&repo_xUbuntu_16_04=1

The packages that could not build are:
- proxy
- shim
- runtime

All of them fail with a similar error: `a.out: final close failed: Invalid operation`

```
[  101s] go build -buildmode=pie -o kata-proxy -ldflags "-X main.version=1.4.0-e1856c2"
[  106s] # github.com/kata-containers/proxy
[  106s] /usr/src/packages/BUILD/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
[  106s] /tmp/go-build704274864/b001/exe/a.out: final close failed: Invalid operation
[  106s] collect2: error: ld returned 1 exit status
```

**Comment by jodh-intel** [comment]
I wonder if `/tmp` filled up somehow? :smile:

**Comment by jcvenegas** [comment]
@jodh-intel  XD I hope not.

I'll try to add some steps to check that.

Also will try to use an old golang version and try to get  gcc in verbose mode.

**Comment by jcvenegas** [comment]
Moving to an old golang version make work probably is an error with cgo and the  gcc version intalled, @devimc @sboeuf @chavafg  let me know if you know a way I can debug more about the linker issues and golang.

**Comment by jcvenegas** [comment]
I'll rebuild with the packages with go 1.10 for the moment, but we need to find what is the issue the gcc in  ubuntu 16.04 and golang 1.11

**Comment by devimc** [comment]
@jcvenegas I'm not sure but that seems like it's a problem with golang and xenial, the latest version of golang supported in xenial is 1.6

```
$ sudo apt show golang-go
Package: golang-go
Version: 2:1.6-1ubuntu4
```

**Comment by GabyCT** [comment]
Closing this issue as we already have obs packages for ubuntu 16.04
