### ISSUE TITLE
Remove EOL distro versions

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#279]
The following distro versions are now unmaintained:

- Fedora 26
- Fedora 27
- Ubuntu 17.10

We need to:

- Remove them from `obs-packaging/distros`.
- Communicate with users on the ML that they need to upgrade to newer distro versions.

Related:

- https://github.com/kata-containers/packaging/pull/267/files#r239923916
- https://github.com/kata-containers/ci/issues/41

**Comment by marcov** [comment]
@jodh-intel can you reopen this, we still need to:

- [ ] Communicate on the ML that these distros are no more supported.
- [ ] Update the install documentation.
- [ ] Remove EOL distros builds on OBS (they are still there for master).

**Comment by jodh-intel** [comment]
@marcov - all yours ;)
