### ISSUE TITLE
build_all: version comparison doesn't take ~ into account for get_versions

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#291]
Example: new version is 1.5.0-rc2, but OBS requires 1.5.0~rc2.  Build all has a sanity check now to compare the versions, and it catches this (currently necessary) hack.  

This was introduced by https://github.com/kata-containers/packaging/commit/c3a371b2b048424b473b4b537d725777f37ab658

**Comment by bergwolf** [comment]
Fix available #292
