### ISSUE TITLE
Kernel build test is not running corretly

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#297]
https://github.com/kata-containers/packaging/blob/master/kernel/build-kernel_test.sh the test should run when patches, configs are modified.

**Comment by GabyCT** [comment]
From issue #269 , it is seen in the logs that the `build-kernel_test.sh` was never executed
```
+ make test
Not changes in release/
Not changes in obs-packaging/
Not changes in static-build/
Not changes in kernel/
```

**Comment by GabyCT** [comment]
@jcvenegas , while running this locally, this line is not detecting changes in the folder of `kernel` for example.
https://github.com/kata-containers/packaging/blob/master/.ci/test.sh#L22

**Comment by GabyCT** [comment]
Closing this issue as `build-kernel_test.sh` does not exist
