### ISSUE TITLE
kata-deploy install script: don't create new configuration for containerd if it already exists

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#307]
Today we just create a new toml, which generally won't exist by default anyway.

Check if file exists, and if it does, insert runtime information into the correct section of toml.

**Comment by olberger** [comment]
I'm afraid this is problematic, in the case where one has to change some settings.

For instance, I had to change the cgroups driver to systemd and used the following way:
```
sudo mkdir -p /etc/containerd
sudo containerd config default | sudo tee /etc/containerd/config.toml

sudo sed -i 's/systemd_cgroup = false/systemd_cgroup = true/g' /etc/containerd/config.toml
```
There may be other ways, but by replacing the script in kata-deploy, I fear my changes will be discarded

**Comment by egernst** [comment]
@olberger — the comment wasn’t completely clear to me.  It sounds like the current scenario is problematic, but the proposed (edit the pre-existing) would meet your needs?  Or?

**Comment by olberger** [comment]
Surely, erasing something that's there is problematic.

So inserting seems better yes.

My scenario was quite weird actually, sorry about the mess.

**Comment by egernst** [comment]
imo, absent more bash kung-fu, we should be appending instead of just backing up the original code
```bash

	cat <<EOT | tee "$containerd_conf_file"
```
https://github.com/kata-containers/packaging/blob/master/kata-deploy/scripts/kata-deploy.sh#L131

**Comment by jodh-intel** [comment]
@egernst - I'd recommend switching the script to use [`crudini`](https://github.com/pixelb/crudini) as the logic is then much simpler. Plus, check out the `--existing[=WHAT]` option which can help with idempotency.

**Comment by egernst** [comment]
okay -- will need to read up on it!

**Comment by jodh-intel** [comment]
This script has quite a few examples for reference: https://github.com/kata-containers/tests/blob/master/.ci/configure_tracing_for_kata.sh.

**Comment by wilsonianb** [comment]
I took a look at `crudini`, but it doesn't seem very toml-friendly (https://github.com/pixelb/crudini/issues/30).
I found [`jq`](https://github.com/dflemstr/rq) as an alternative solution which I used in that [pr](https://github.com/kata-containers/packaging/pull/605) :point_up:

**Comment by wilsonianb** [comment]
On second thought, `crudini` should work if we're ok losing indentation in the containerd config (as seen here: https://github.com/wilsonianb/packaging/commit/63d7a3d2cdc2e97e867dc969fd9434a80fc95203).
If that sounds reasonable, I'll submit that as a pr.

**Comment by jodh-intel** [comment]
@egernst - wdyt?

/cc @chavafg who introduced us to `crudini` I think ;)
