### ISSUE TITLE
guest kernel: add memory hotplug support for arm64 using "probe"

### ISSUE THREAD

**Issue by jongwu** [kata-containers/packaging#309]
now memory hotplug is not ready on guest kernel on arm64, and acpi method is not presented on qemu for arm64, so we choose memory probe by hand method to enable memory hotplug for arm64. @jon @liwei @jbryce @gnawux

**Comment by devimc** [comment]
cc @Weichen81 @Pennyzct

**Comment by jongwu** [comment]
@jcvenegas yeah, the flow chart of memory hotplug by probe will be adding memory in qemu monitor, echo address to /sys/..../memory/probe in guest by agent, then guest kernel will know this memory and adding it to memory pool. to implement all of these, we need supports from qemu,whose patch is under review, kata-agent and guest kernel. both @Pennyzct and I will do all of these, and as for me, I will be responsible for kernel part.

**Comment by Pennyzct** [comment]
Hi~@jcvenegas  I'm already patching the hole in `kata-runtime `and `kata-agent` and intending to wait for the kernel part landed firstly. Maybe I should upload the related code with this issue altogether to get better, clear view of how we planed to do memory hotplug by probe interface on aarch64. ;)

**Comment by Pennyzct** [comment]
Hi~ @jcvenegas I've already uploaded related code into `runtime/` and `agent/` .

**Comment by jiayang-zheng** [comment]
> @jcvenegas yeah, the flow chart of memory hotplug by probe will be adding memory in qemu monitor, echo address to /sys/..../memory/probe in guest by agent, then guest kernel will know this memory and adding it to memory pool. to implement all of these, we need supports from qemu,whose patch is under review, kata-agent and guest kernel. both @Pennyzct and I will do all of these, and as for me, I will be responsible for kernel part.


Hi JongWu, could you help to point out which patch in qemu is supporting mem hotplug please?
I installed a kata-runtime on aarch64, and built qemu using test/.ci/install_qemu.sh，which helps to patch the [Eric Auger's latest PCDIMM/NVDIMM patches](https://patchwork.kernel.org/cover/10647305/) automatically, but it seems not the right patch - when I run "docker run --runtime kata-runtime -it --rm -m 3G ubuntu", it returns:
"docker: Error response from daemon: OCI runtime create failed: QMP command failed: memory hotplug is not supported"

So could you help on that, please? @jongwu
