### ISSUE TITLE
static tarball: need to add firecracker, and indirection for multi-hypervisor support

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#315]
prior PR added what's needed for building firecracker into the static tarball, but the function isn't exercised today.

* need to build/install firecracker binary
* need to add indirection for kata-fc and kata-qemu which'll utilize their specific config toml

**Comment by jodh-intel** [comment]
For reference, I think that PR is #303.

Related to the FC `configuration.toml`: https://github.com/kata-containers/runtime/pull/1109.
