### ISSUE TITLE
snap: bad commit version

### ISSUE THREAD

**Issue by devimc** [kata-containers/packaging#317]
```
$ kata-containers.runtime --version
kata-runtime  : 1.5.0-rc2
   commit   : f802dd879631729c62216ac092c0094c34dd740f-dirty
   OCI specs: 1.0.1-dev
```

**Comment by jodh-intel** [comment]
Ouch! That's from the packaging repo (tag `1.5.0-kernel-config`) rather than the `1.5.0-rc2` tag representing runtime repo commit `b954eecad14de13e09dfab89a8b902f1cb05a041`.

**Comment by grahamwhaley** [comment]
@devimc @chavafg Is this fixed?
I just installed/ran up the 'current' snap, and found that it also did not have a QEMU called qemu-lite, even though it seems that is what the default config is looking for. I think you may have mentioned and know that already - is that also fixed, or has an Issue/PR in flight?

**Comment by devimc** [comment]
@grahamwhaley nop, they are fixed here https://github.com/kata-containers/packaging/pull/318, thanks
