### ISSUE TITLE
Fix install doc links in runtime-release-notes.sh

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#320]
As reported by @fredbcode on https://github.com/kata-containers/runtime/issues/1184, the "installation instructions" link on https://github.com/kata-containers/runtime/releases is incorrect.

For example for [1.5.0](https://github.com/kata-containers/runtime/releases/1.5.0) the link refers to:

- https://github.com/kata-containers/runtime/blob/1.5.0/installation

That's incorrect for 2 reasons:

- We don't currently [branch the doc repo](https://github.com/kata-containers/documentation/issues/246) when we make a release.
- The installation instructions are in the doc repo at https://github.com/kata-containers/documentation/tree/master/install. 

The problem is:

- https://github.com/kata-containers/packaging/blob/master/release/runtime-release-notes.sh#L148

**Comment by jodh-intel** [comment]
How distressing, github seems to lack a Slack-like dancing multi coloured parrot emoji :cry:

**Comment by grahamwhaley** [comment]
It does however have: 🦄

**Comment by jodh-intel** [comment]
Nice - and :rainbow: 's
