### ISSUE TITLE
kata-deploy: add runtimeClass for containerd configuration

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#323]
Currently we still utilize trusted/untrusted when configuring containerd via kata-deploy.

Need to migrated to using runtimeClass (and be consistent with the CRIO configuration).

**Comment by bergwolf** [comment]
It's worth noting that for containerd, the preferred setup is `k8s + runtimeclass + containerd + containerd-shim-kata-v2`

**Comment by egernst** [comment]
Totally agree. That’s next!
