### ISSUE TITLE
Delete old OBS "release" URL

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#325]
# History

When we first started providing Open Build Service (OBS) distro packages for Kata, we used this URL:

- https://download.opensuse.org/repositories/home:/katacontainers:/release/

However, when we added support for different architectures, we [changed](https://github.com/kata-containers/documentation/pull/256) the [installation documentation](https://github.com/kata-containers/documentation/tree/master/install) to use a URL containing two additional pieces of information:

- architecture (`x86_64` for example).
- git branch packages are built from (`master`).

The installation URL therefore changed from "release" to a "releases" URL like the following:

- https://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_18.04/

# Problem

We decided to retain the old "release" URL to allow existing installations to continue to use it (on `x86_64` only, being the only architecture we originally provided). However, that has proven to be problematic since:

- it's confusing people.
- we've had problems keeping the "release" URL in sync with the "releases" URL it is populated from.

# Solution

Delete the old "release" URL. This will force an HTTP 404 error so users will know something has changed. Once deleted, we will notify users by posting to the public mailing list that the change has occurred.

## Additional Benefit

By removing that old "release" URL, we should consume less space on OBS, and simplify our setup.

# See also

See: https://github.com/kata-containers/runtime/issues/1184.

**Comment by jodh-intel** [comment]
Hi @marcov, as we have I think 5 acks and no nacks on https://github.com/kata-containers/runtime/issues/1184 for this plan, please can you go ahead and delete the original "release" URL on OBS, and remove any additional scripts/config that was populating that area?

We can then notify users on http://lists.katacontainers.io/pipermail/kata-dev/ about the change and suggest they delete their old Kata packages and re-install from:

- https://github.com/kata-containers/documentation/tree/master/install.

/cc @jcvenegas, @egernst, @gnawux.

**Comment by marcov** [comment]
@jodh-intel, sure!

I did a quick grep on all the kata git repos, and I have found a couple of references to  the "release" link:
- https://github.com/kata-containers/documentation/blob/master/zun/zun_kata.md#install-kata-runtime-kata-shim-and-kata-proxy
- https://github.com/kata-containers/packaging/blob/master/ccloudvm/kata-docker-xenial.yaml

I'll update these 2 to use the correct links, and then proceed to remove the "release" subproject on OBS.

**Comment by jodh-intel** [comment]
Thanks @marcov!

**Comment by marcov** [comment]
That's it. Users notified on kata-dev, project deleted and binaries wiped. 

@jodh-intel you can close this now.

**Comment by jodh-intel** [comment]
Thanks @marcov ! Closing...
