### ISSUE TITLE
snap build config scripts should not hard-code ubuntu version

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#349]
```sh
$ cd $GOPATH/src/github.com/kata-containers/packaging/snap-build
$ egrep "local arch_image.*=" config_*.sh
config_amd64.sh:local arch_image="bionic-server-cloudimg-amd64.img"
config_amd64.sh:local arch_image_url="https://cloud-images.ubuntu.com/bionic/current/${arch_image}"
config_arm64.sh:local arch_image="bionic-server-cloudimg-arm64.img"
config_arm64.sh:local arch_image_url="https://cloud-images.ubuntu.com/bionic/current/${arch_image}"
config_ppc64.sh:local arch_image="bionic-server-cloudimg-ppc64el.img"
config_ppc64.sh:local arch_image_url="https://cloud-images.ubuntu.com/bionic/current/${arch_image}"
config_s390x.sh:local arch_image="bionic-server-cloudimg-s390x.img"
config_s390x.sh:local arch_image_url="https://cloud-images.ubuntu.com/bionic/current/${arch_image}"
```

Since all architectures are specifying (Ubuntu bionic) in their config files, we should create a `config_common.sh` or similar that they can all source to avoid the duplication. Same argument regarding the url - we could create a function in `config_common.sh` that generates the url.

The ideal would be to create a `versions.yaml` for this repo too, as we do for:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml
- https://github.com/kata-containers/tests/blob/master/versions.yaml

**Comment by devimc** [comment]
see https://github.com/kata-containers/packaging/issues/350
