### ISSUE TITLE
obs: Seems like obs is redirecting to `release` url

### ISSUE THREAD

**Issue by chavafg** [kata-containers/packaging#357]
Today we started seen an error on the CI when trying to add the Kata OBS repository:

```
Install Kata Containers OBS repository
Loaded plugins: fastestmirror
adding repo from: http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_7/home:katacontainers:release.repo
grabbing file http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_7/home:katacontainers:release.repo to /etc/yum.repos.d/home:katacontainers:release.repo
Could not fetch/save url http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_7/home:katacontainers:release.repo to file /etc/yum.repos.d/home:katacontainers:release.repo: [Errno 14] HTTP Error 404 - Not Found
Build step 'Execute shell' marked build as failure
```
From: http://jenkins.katacontainers.io/job/kata-containers-runtime-centos-7-4-PR/1253/console

I verified that our CI scripts use the `releases` URL:
https://github.com/kata-containers/tests/blob/master/.ci/lib.sh#L29

So it seems strange that for some reason, we are being redirected to the `release` url. Might this be a problem in the OBS mirrors?

**Comment by marcov** [comment]
to me it looks like it is cloning an old version of the tests repository instead of master, and that version still contains the old URL.

The `repo_file` is now named `master.repo`, while in the logs it is still being called `release.repo`.

**Comment by chavafg** [comment]
Thanks @marcov 
yeah, sorry for the noise. This happened on stable branches 1.4 and 1.5. Opened a couple of PRs to fix this. 
Related
https://github.com/kata-containers/tests/pull/1229
https://github.com/kata-containers/tests/pull/1230

**Comment by chavafg** [comment]
closing issue.
