### ISSUE TITLE
My own compiled kernel kata can not run

### ISSUE THREAD

**Issue by free2k** [kata-containers/packaging#375]
https://github.com/kata-containers/packaging/tree/master/kernel
According to this document, the kata kernel is compiled by itself, but it cannot be run. The kernel version I am using is 3.10。

https://github.com/kata-containers/packaging/tree/master/kernel/configs
There are only config files for the kernels of 4.14 and 4.19, does it mean that only kernels of 4.14 and 4.19 are supported?

If you run the compiled kernel 3.10, you will get an error.
“ docker run --runtime kata-runtime --name kata-test --cpus 8 --memory 8G -itd daocloud.io/library/centos  /bin/sh
5290a918909b660efd139a46c3c2183608b5259555b7d725c8bc389aac6c9b01

/usr/bin/docker-current: Error response from daemon: oci runtime error: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing.”

**Comment by jodh-intel** [comment]
Hi @free2k - if you enable full debug, the proxy should log guest kernel boot message to the host systemd journal. See:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug
- https://github.com/kata-containers/tests/tree/master/cmd/log-parser#usage

**Comment by grahamwhaley** [comment]
@free2k - if you cannot find what is wrong and need more help, please also attach your kernel v3.10 config file you used with the packaging kernel build so we can examine and maybe re-create.
Initially I am wondering if the kernel v3.10 is so old it will not have some features (like nvdimm/DAX) which kata can use - so examine the runtime/qemu logs and the kernel dmesg output maybe for clues.

**Comment by free2k** [comment]
### Output log

`Record 2892: {Count:2892 TimeDelta:35716 Filename:/root/kata/tmp/runtime.log Line:2858 Time:2019-03-05 19:13:05.709481257 +0800 CST Pid:7051 Level:info Msg:launching qemu with: [-naa
me sandbox-b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 -uuid 5af2fb84-e30f-4649-84df-8695bfc9a57b -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unii
x:/run/vc/vm/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329/qmp.sock,server,nowait -m 8192M,slots=10,maxmem=16817M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chaa
ssis_nr=1,shpc=on,addr=2 -device virtio-serial-pci,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/b87430f9f1f787676cc
46a31e21afa658513903dda5b6d02e41e48131b8010329/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kk
ata-containers-image_clearlinux_1.3.0_agent_042c3ebd71c.img,size=536870912 -device virtio-scsi-pci,id=scsi0 -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng,rng=rr
ng0 -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b801033
29/kata.sock,server,nowait -device virtio-9p-pci,fsdev=extra-9p-kataShared,mount_tag=kataShared -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/b874300
f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac==
02:42:ac:11:00:02,mq=on,vectors=4 -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/kata-containers/vmlinuz-3.11
0.0-23 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommuu
=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_levell
=debug panic=1 nr_cpus=8 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket agent.log=debugg
 initcall_debug -smp 1,cores=1,threads=1,sockets=1,maxcpus=8] Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandd
box: Data:map[arch:amd64 command:create subsystem:qmp]}
Record 2893: {Count:2893 TimeDelta:94614928 Filename:/root/kata/tmp/runtime.log Line:2859 Time:2019-03-05 19:13:05.804096185 +0800 CST Pid:7051 Level:info Msg:{"QMP": {"version": {""
qemu": {"micro": 0, "minor": 11, "major": 2}, "package": ""}, "capabilities": []}} Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02ee
41e48131b8010329 Sandbox: Data:map[command:create subsystem:qmp arch:amd64]}
Record 2894: {Count:2894 TimeDelta:139297 Filename:/root/kata/tmp/runtime.log Line:2860 Time:2019-03-05 19:13:05.804235482 +0800 CST Pid:7051 Level:info Msg:QMP details Source:virtcc
ontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[qmp-minor-version:11 subsystem:qemu arch:amd64 command:creatt
e qmp-capabilities: qmp-major-version:2 qmp-micro-version:0]}
Record 2895: {Count:2895 TimeDelta:72404 Filename:/root/kata/tmp/runtime.log Line:2861 Time:2019-03-05 19:13:05.804307886 +0800 CST Pid:7051 Level:info Msg:{"execute":"qmp_capabilitt
ies"} Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:qmp]}
Record 2896: {Count:2896 TimeDelta:134007 Filename:/root/kata/tmp/runtime.log Line:2862 Time:2019-03-05 19:13:05.804441893 +0800 CST Pid:7051 Level:info Msg:{"return": {}} Source:vii
rtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:qmp]}
Record 2897: {Count:2897 TimeDelta:71335 Filename:/root/kata/tmp/runtime.log Line:2863 Time:2019-03-05 19:13:05.804513228 +0800 CST Pid:7051 Level:info Msg:VM started Source:virtconn
tainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Data:maa
p[subsystem:sandbox arch:amd64 command:create]}
Record 2898: {Count:2898 TimeDelta:37538 Filename:/root/kata/tmp/runtime.log Line:2864 Time:2019-03-05 19:13:05.804550766 +0800 CST Pid:7051 Level:info Msg:Starting regular Kata proo
xy rather than built-in Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox:b87430f9f1f787676c46a31e21afa658511
3903dda5b6d02e41e48131b8010329 Data:map[arch:amd64 command:create subsystem:kata_agent]}
Record 2899: {Count:2899 TimeDelta:149133 Filename:/root/kata/tmp/runtime.log Line:2865 Time:2019-03-05 19:13:05.804699899 +0800 CST Pid:7051 Level:info Msg:proxy started Source:virr
tcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Datt
a:map[arch:amd64 command:create proxy-pid:7091 proxy-url:unix:///run/vc/sbs/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329/proxy.sock subsystem:kata_agent]}
Record 2900: {Count:2900 TimeDelta:45684 Filename:/root/kata/tmp/runtime.log Line:2866 Time:2019-03-05 19:13:05.804745583 +0800 CST Pid:7051 Level:info Msg:New client Source:virtconn
tainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:kata_agent url:unix:///runn
/vc/sbs/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329/proxy.sock]}
Record 2901: {Count:2901 TimeDelta:950715 Filename:/root/kata/tmp/proxy.log Line:35 Time:2019-03-05 19:13:05.805696298 +0800 CST Pid:7091 Level:info Msg:announce Source:proxy Name:kk
ata-proxy Container: Sandbox:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Data:map[agent-logs-socket:/run/vc/vm/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e44
1e48131b8010329/console.sock channel-mux-socket:/run/vc/vm/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329/kata.sock debug:true log-level:debug proxy-listen-socket::
unix:///run/vc/sbs/b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329/proxy.sock version:1.3.0-6ddb006]}
Record 2902: {Count:2902 TimeDelta:420513 Filename:/root/kata/tmp/runtime.log Line:2867 Time:2019-03-05 19:13:05.806116811 +0800 CST Pid:7051 Level:debug Msg:sending request Source::
virtcontainers Name:grpc.CheckRequest Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create req: subsystem:kata_agenn
t]}
Record 2903: {Count:2903 TimeDelta:19999017713 Filename:/root/kata/tmp/runtime.log Line:2868 Time:2019-03-05 19:13:25.805134524 +0800 CST Pid:7051 Level:info Msg:Stopping Sandbox Soo
urce:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[command:create subsystem:qemu arch:amd64]}
Record 2904: {Count:2904 TimeDelta:77433 Filename:/root/kata/tmp/proxy.log Line:36 Time:2019-03-05 19:13:25.805211957 +0800 CST Pid:7091 Level:fatal Msg:failed to handle exit signall
 Source:proxy Name:kata-proxy Container: Sandbox:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Data:map[error:close unix @->/run/vc/vm/b87430f9f1f787676c46a31e21aa
fa658513903dda5b6d02e41e48131b8010329/kata.sock: use of closed network connection]}
Record 2905: {Count:2905 TimeDelta:130006 Filename:/root/kata/tmp/runtime.log Line:2869 Time:2019-03-05 19:13:25.805341963 +0800 CST Pid:7051 Level:info Msg:{"QMP": {"version": {"qee
mu": {"micro": 0, "minor": 11, "major": 2}, "package": ""}, "capabilities": []}} Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e411
e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:qmp]}
Record 2906: {Count:2906 TimeDelta:159876 Filename:/root/kata/tmp/runtime.log Line:2870 Time:2019-03-05 19:13:25.805501839 +0800 CST Pid:7051 Level:info Msg:{"execute":"qmp_capabilii
ties"} Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:qmp]}
Record 2907: {Count:2907 TimeDelta:128235 Filename:/root/kata/tmp/runtime.log Line:2871 Time:2019-03-05 19:13:25.805630074 +0800 CST Pid:7051 Level:info Msg:{"return": {}} Source:vii
rtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[subsystem:qmp arch:amd64 command:create]}
Record 2908: {Count:2908 TimeDelta:57614 Filename:/root/kata/tmp/runtime.log Line:2872 Time:2019-03-05 19:13:25.805687688 +0800 CST Pid:7051 Level:info Msg:{"execute":"quit"} Sourcee
:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:qmp]}
Record 2909: {Count:2909 TimeDelta:93901 Filename:/root/kata/tmp/runtime.log Line:2873 Time:2019-03-05 19:13:25.805781589 +0800 CST Pid:7051 Level:info Msg:{"return": {}} Source:virr
tcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[command:create subsystem:qmp arch:amd64]}
Record 2910: {Count:2910 TimeDelta:37557 Filename:/root/kata/tmp/runtime.log Line:2874 Time:2019-03-05 19:13:25.805819146 +0800 CST Pid:7051 Level:info Msg:{"timestamp": {"seconds"::
 1551784405, "microseconds": 805777}, "event": "SHUTDOWN", "data": {"guest": false}} Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d00
2e41e48131b8010329 Sandbox: Data:map[subsystem:qmp arch:amd64 command:create]}
Record 2911: {Count:2911 TimeDelta:82711 Filename:/root/kata/tmp/runtime.log Line:2875 Time:2019-03-05 19:13:25.805901857 +0800 CST Pid:7051 Level:info Msg:Detaching endpoint Sourcee
:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create endpoint-type:virtual subsyss
tem:network]}
Record 2912: {Count:2912 TimeDelta:16172214 Filename:/root/kata/tmp/runtime.log Line:2876 Time:2019-03-05 19:13:25.822074071 +0800 CST Pid:7051 Level:debug Msg:Network removed Sourcc
e:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandbox: Data:map[arch:amd64 command:create subsystem:default-network]}
Record 2913: {Count:2913 TimeDelta:41076 Filename:/root/kata/tmp/runtime.log Line:2877 Time:2019-03-05 19:13:25.822115147 +0800 CST Pid:7051 Level:info Msg:Network namespace "/var/rr
un/netns/cni-3d808b60-5a01-2492-0fd8-3c1c64b2eefa" deleted Source:virtcontainers Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Sandboxx
: Data:map[arch:amd64 command:create subsystem:default-network]}
Record 2914: {Count:2914 TimeDelta:10761086 Filename:/root/kata/tmp/runtime.log Line:2878 Time:2019-03-05 19:13:25.832876233 +0800 CST Pid:7051 Level:error Msg:Failed to check if grr
pc server is working: rpc error: code = Unavailable desc = transport is closing Source:runtime Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b88
010329 Sandbox: Data:map[command:create arch:amd64]}
Record 2915: {Count:2915 TimeDelta:55390629 Filename:/root/kata/tmp/runtime.log Line:2879 Time:2019-03-05 19:13:25.888266862 +0800 CST Pid:7115 Level:info Msg:loaded configuration SS
ource:runtime Name:kata-runtime Container: Sandbox: Data:map[arch:amd64 command:delete file:/usr/share/defaults/kata-containers/configuration.toml format:TOML]}
Record 2916: {Count:2916 TimeDelta:116763 Filename:/root/kata/tmp/runtime.log Line:2880 Time:2019-03-05 19:13:25.888383625 +0800 CST Pid:7115 Level:info Msg: Source:runtime Name:katt
a-runtime Container: Sandbox: Data:map[arch:amd64 arguments:"delete b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329" command:delete commit:a786643 version:1.3.0]}
Record 2917: {Count:2917 TimeDelta:72964 Filename:/root/kata/tmp/runtime.log Line:2881 Time:2019-03-05 19:13:25.888456589 +0800 CST Pid:7115 Level:error Msg:Container ID (b87430f9f11
f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329) does not exist Source:runtime Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Saa
ndbox: Data:map[arch:amd64 command:delete]}
Record 2918: {Count:2918 TimeDelta:34155430 Filename:/root/kata/tmp/runtime.log Line:2882 Time:2019-03-05 19:13:25.922612019 +0800 CST Pid:7124 Level:info Msg:loaded configuration SS
ource:runtime Name:kata-runtime Container: Sandbox: Data:map[file:/usr/share/defaults/kata-containers/configuration.toml format:TOML arch:amd64 command:delete]}
Record 2919: {Count:2919 TimeDelta:103625 Filename:/root/kata/tmp/runtime.log Line:2883 Time:2019-03-05 19:13:25.922715644 +0800 CST Pid:7124 Level:info Msg: Source:runtime Name:katt
a-runtime Container: Sandbox: Data:map[version:1.3.0 arch:amd64 arguments:"delete b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329" command:delete commit:a786643]}
Record 2920: {Count:2920 TimeDelta:50571 Filename:/root/kata/tmp/runtime.log Line:2884 Time:2019-03-05 19:13:25.922766215 +0800 CST Pid:7124 Level:error Msg:Container ID (b87430f9f11
f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329) does not exist Source:runtime Name:kata-runtime Container:b87430f9f1f787676c46a31e21afa658513903dda5b6d02e41e48131b8010329 Saa
ndbox: Data:map[arch:amd64 command:delete]`

**Comment by free2k** [comment]
@grahamwhaley I looked at it but didn't find out where the problem was.

**Comment by jodh-intel** [comment]
Thanks @free2k. However, you don't appear to have enabled full debug - there are no messages from the agent or the guest kernel fwics. Please can you ensure you run both `sed` commands here:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug

**Comment by grahamwhaley** [comment]
I suspect that may have just been the runtime log - yes, enabling full debug and then looking in the proxy log (so we can get the kernel boot log out from the agent messages) might help indeed. Sorry if we didn't state that yesterday! ;-)

**Comment by clarklee92** [comment]
> @grahamwhaley I looked at it but didn't find out where the problem was.

Hi, did you run 3.10 with kata finally? Pelease give ma a reply ,we do need this version too. 
Thank you very much!

**Comment by grahamwhaley** [comment]
Just to check/clarify then - you are trying to use kernel v3.10 as the VM kernel image (not the host).
My suspicion is there are a number of features that will not be available to Kata to use - specifically I am thinking:
- vsocks (which maybe you can live without as kata can work without vsocks, but *note*, we are more and more moving towards vsocks)
- DAX/NVDIMM - which iirc may have come into a much later kernel. I *think* support is required in the VM kernel - in which case, you may have to do some more extensive Kata configuration (possibly even code changes) to support.

@devimc wdyt?

**Comment by devimc** [comment]
@grahamwhaley @clarklee92 @free2k yes, there are a lot of limitations in the kernel 3.10. also this kernel crashes when using scsi and a CPU is hot plugged

**Comment by devimc** [comment]
I couldn't run a container with the kernel 3.10, 
* NVDIMM is not supported (fortunately kata also supports initrd)
* agent couldn't start: `failed to setup agent as init: open /sys/fs/cgroup/memory/memory.use_hierarchy: no such file or directory`

if you have plans to use kernel 3.10, you will need to patch the agent too
