### ISSUE TITLE
Package a kernel with virtio-fs patches

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/packaging#387]
In order to support an early version of `virtio-fs`, we should package a kernel that supports it. [Here](https://gitlab.com/virtio-fs/linux) are the patches.

There are two options to proceed here:
- We port the patches on top of our 4.19.XX kernel. I'm worried this might be a complex task.
OR
- We package a special kernel directly out of the virtio-fs branch, applying our kernel config along with the config options required by virtio-fs. We would not need to automate this, it's mostly a matter of getting the kernel manually ready and push it to our package repository.

/cc @egernst @jcvenegas WDYT?

**Comment by jcvenegas** [comment]
I prefer we move to 4.20 ?

**Comment by jcvenegas** [comment]
@sboeuf  if we want to go to the second option , about just get the kernel manually and push it to the packaging repository I prefer just publish it somewhere else, a webserver or even jenkins for demo.

**Comment by sboeuf** [comment]
@jcvenegas 
>I prefer we move to 4.20 ?

This could be another option, but if we first need to move to 4.20, this will introduce one more dependency on getting this done.

@sameo @egernst WDYT?

**Comment by sameo** [comment]
> We package a special kernel directly out of the virtio-fs branch, applying our kernel config along with the config options required by virtio-fs. We would not need to automate this, it's mostly a matter of getting the kernel manually ready and push it to our package repository.

I'd prefer to avoid this and have a reproducible way of building our virtio-fs kernel instead. Are the virtio-fs self contained, or back porting them to 4.19 be a real pain? Having a virtio-fs branch from our main kernel tree, and building kernel from there would be the cleaner option imho.

**Comment by sboeuf** [comment]
@sameo 
>I'd prefer to avoid this and have a reproducible way of building our virtio-fs kernel instead.

If that's all that matters, then we can definitely automate a simple script relying on the linux kernel branch with the virtio-fs patches directly.

>Are the virtio-fs self contained, or back porting them to 4.19 be a real pain?

Depends on what you consider self contained. Most of them are modifying files inside `fs/fuse/` directory. A few patches slightly modify the DAX driver.
I don't know if a lot of things changed between 4.19.24 and the upstream wrt `fs/fuse/`, but this could be the biggest blocker.
Okay instead of talking, I guess the best way is to try to apply them on our 4.19.24 kernel and see what happens!

If we can go down this route, we will have to adapt the packaging scripts to be able to build one kernel with the patches and another kernel without the patches. Or do we want to get those patches in all our Kata kernels?

>Having a virtio-fs branch from our main kernel tree, and building kernel from there would be the cleaner option imho.

I agree, I'm just trying to assess how much effort we want to put into this.

**Comment by sameo** [comment]
>  > I'd prefer to avoid this and have a reproducible way of building our virtio-fs kernel instead.
>
> If that's all that matters, then we can definitely automate a simple script relying on the linux kernel branch with the virtio-fs patches directly.

So the problem with that is that we're now testing 2 different kernel code bases and we're adding another parameter to our CI matrix.

> If we can go down this route, we will have to adapt the packaging scripts to be able to build one kernel with the patches and another kernel without the patches. Or do we want to get those patches in all our Kata kernels?

Maybe we should consider keeping one single kernel and one single branch, but 2 different config files: one with virtio-fs enable, and the main one with it disabled.

**Comment by jcvenegas** [comment]
@sboeuf  if they apply correctly 

> Maybe we should consider keeping one single kernel and one single branch, but 2 different config files: one with virtio-fs enable, and the main one with it disabled.

Even to configs would increase the testing matrix, if they are enabled by default would be great, I wonder if config fragments can deal,  I think yes, so if the kernel has a kconfig option for virtio-fs this is going to be enabled if not this is removed @grahamwhaley.

**Comment by sboeuf** [comment]
@sameo 
>Maybe we should consider keeping one single kernel and one single branch, but 2 different config files: one with virtio-fs enable, and the main one with it disabled.

If the porting works without issues, then this sounds like the best approach. This way, we could ask only the CI testing virtio-fs to build the kernel from source with a different config file.
But if we want to rely/provide kernel packages, we would still end up with 2 binaries.

**Comment by grahamwhaley** [comment]
fragments - you could split the special bits into their own 'fragment file', and then have the scripts chose which frags to use or not (the easiest way is to delete/mv the ones you don't want to use out of the way ... and then they just won't get picked up).
Speaking of which, the [frags PR](https://github.com/kata-containers/packaging/pull/314#issuecomment-468279159) is blowing the CI (iirc, only one one distro maybe), and I've not had a chance to go chase it.

**Comment by sboeuf** [comment]
@sameo I've tried the port of the patches on top of `4.19.27`, but unfortunately, I had to manually resolve some conflicts because some modifications have been introduced between 4.19 and the upstream virtio-fs branch. And unfortunately, after I resolved all conflicts, it couldn't build...

So I'm gonna say that with more efforts we might get this to work, but there are some `fs/fuse` commits dependencies that need to be found and solved.

**Comment by sboeuf** [comment]
It's been discussed with the community that
- Having a single kernel would be easier, and the virtio-fs patches should not impact Kata as they are contained.
- We want to move to kernel 4.20.x or 5.0.x after we cut release 1.6 on March 20th. Patches will apply easily and would be part of the Kata default kernel. Which version do we want to pick?

@bergwolf @WeiZhang555 @sameo @egernst @gnawux are you okay with all this? Should we proceed with this plan?

**Comment by egernst** [comment]
Did anyone do a metrics run on the proposed kernel with the feature enabled yet?

Similar for our existing config on 4.20.x.

**Comment by egernst** [comment]
let's get a formal ACK from the @kata-containers/architecture-committee [on the proposal](https://docs.google.com/document/d/1oc467vctWcxcfzuoXWCFnjPrLXTbDfJzVv67HbGAUrw/edit?ts=5c9e68ec#heading=h.greyp0m0li6d)
