### ISSUE TITLE
OBS packages failed in SLES 12 SP3

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/packaging#39]
Currently kata-shim and kata-proxy is not being installed at:
/usr/libexec/kata-containers

```
$ sudo docker run -ti busybox sh
Message from syslogd@linux at May 21 19:08:59 ...
 sr/share/defaults/kata-containers/configuration.toml: file /usr/libexec/kata-containers/kata-shim does not exist
docker: Error response from daemon: oci runtime error: /usr/share/defaults/kata-containers/configuration.toml: file /usr/libexec/kata-containers/kata-shim does not exist.

$ sudo find / -iname kata-shim
/usr/lib64/kata-containers/kata-shim
```

**Comment by GabyCT** [comment]
@jcvenegas the same is happening with the packages for openSUSE Leap 42.3
```
$ find / -iname kata-shim
/usr/lib64/kata-containers/kata-shim
```

**Comment by jodh-intel** [comment]
@jcvenegas, @GabyCT - is this still a problem? It would be great if we could add SuSE to the fold... :)

**Comment by jcvenegas** [comment]
I did not worked on this issue so is the same. If someone want to take a look would be great ;).

**Comment by chavafg** [comment]
also `kata-proxy` is shipped on `/usr/lib64/kata-container`

**Comment by jodh-intel** [comment]
Hi @GabyCT - Looking at the spec files below:

- https://github.com/kata-containers/packaging/blob/master/obs-packaging/shim/kata-shim.spec-template#L7..L11
- https://github.com/kata-containers/packaging/blob/master/obs-packaging/proxy/kata-proxy.spec-template#L9..L13

... it appears that all we might need to do is remove the suse-specific test so that those blocks become:

```
%define LIBEXECDIR %{_libexecdir}
```

To test this, please can you run the following on your SLES system and paste the results here:

```
$ rpmbuild -E '%{_libexecdir}'
$ rpmbuild -E '%{_libdir}'
```

For reference, a F27 system shows the following:

```
$ rpmbuild -E '%{_libexecdir}'
/usr/libexec
$ rpmbuild -E '%{_libdir}'
/usr/lib64
```

**Comment by GabyCT** [comment]
@jodh-intel let me take a look

**Comment by GabyCT** [comment]
@jodh-intel , here are the results
```
$ rpmbuild -E '%{_libexecdir}'
/usr/lib
$ rpmbuild -E '%{_libdir}'
/usr/lib64
```

**Comment by jodh-intel** [comment]
Hi @GabyCT - great - therefor it does appear we can drop the `if` test but need to test this.

@jcvenegas - does this look sane to you? I'm not sure why we needed that test originally (looks like EricC added it).

**Comment by amshinde** [comment]
@jodh-intel by the results above, looks like %{_libexecdir} is pointing to /usr/lib instead of /usr/libexec on Opensuse. This link confirms it as well
https://en.opensuse.org/openSUSE:Specfile_guidelines

We might need to do some special handling for libexecdir afterall for Opensuse.

**Comment by jodh-intel** [comment]
@amshinde - ouch! I think I need a eye-test! You are indeed correct meaning we do need to retain that fix on https://github.com/kata-containers/documentation/pull/114 after all.

**Comment by GabyCT** [comment]
Closing this issue as it was already fixed
