### ISSUE TITLE
snap-aarch64: modify qemu-related info for arm64

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/packaging#399]
Former snap configuration snapcraft.toml install qemu-lite for all platforms, which isn't applicable on aarch64. We need qemu-aarch64 of specific version and extra patches.
related pr on the way.;)

**Comment by devimc** [comment]
@Pennyzct the new release candidate should include your changes, you can install it running the following command:

```
sudo snap install kata-containers --candidate --classic
```

Thanks
