### ISSUE TITLE
Packaging NEMU and virtiofsd starting with release 1.7

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/packaging#401]
As discussed with the community in the context of supporting virtio-fs through Kata Containers, we will use NEMU as the test vehicle. Once NEMU will be rebased and patched with virtio-fs patches, it will include the feature we need to support virtio-fs from Kata.
We will need to include NEMU as part of the Kata Containers packages so that users can play with virtio-fs.
Also, the virtiofsd daemon binary should be generated by the NEMU project, and this should also be packaged by Kata Containers.

Summary being, we want both `nemu` and `virtiofsd` to be part of the release 1.7 packages.

**Comment by egernst** [comment]
Dependent on:
https://github.com/intel/nemu/issues/206
https://github.com/intel/nemu/issues/211
