### ISSUE TITLE
kata-deploy: remove legacy annotations from examples

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#403]
I think the kata-deploy examples are still carrying the legacy 'trusted' style annotations, which can now be dropped:

https://github.com/kata-containers/packaging/blob/master/kata-deploy/examples/test-deploy-kata-qemu.yaml#L14-L16

@egernst @mcastelino @ganeshmaharaj - if you confirm, I can PR. I think it is only the qemu example that is carrying them?

**Comment by egernst** [comment]
Yes, I confirm @grahamwhaley -- thanks!
