### ISSUE TITLE
kata-deploy: should runtimeClass yaml files be present here?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#404]
Over at https://github.com/clearlinux/cloud-native-setup/tree/master/clr-k8s-examples/8-kata we have a couple of k8s yaml files that add the kata-qemu and kata-fc to the runtimeclass to allow container deploys. Should those files be mirror'd/included/mastered in the packaging/kata-deploy directory instead/aswell?

afaict, right now we have the kata-deploy.yaml which will install the runtime components into a node, but then have no runtimeClass yaml (in this repo) to enable them to be used.

/cc @egernst @mcastelino @ganeshmaharaj

**Comment by egernst** [comment]
Now that runtimeClass is out of feature gate, I think this does make sense @grahamwhaley .  I was hesitant before since the cluster would need to create the CRD, and have the feature gates removed...

Thanks - happy to have another contributor here!

**Comment by grahamwhaley** [comment]
I'll let @mcastelino make the call on what ultimately lives where - I think he has a master plan...

**Comment by egernst** [comment]
It didn’t make sense before. Now that 1.14 supports it, I think it could make sense. The downside, however, is that the kata-deploy becomes k8s version specific. Perhaps we should wait for a period of time, but update documentation To make this clear.

**Comment by grahamwhaley** [comment]
@egernst I was wondering earlier, is it possible do we know to make a yaml file that will apply to either alpha or beta - is there a way to maybe predicate the sections in the yaml so it cherry picks which ones to apply? I'm guessing maybe not. In which case, maybe we need two yaml files for the minute - one 'beta' one and one 'production' one (that will also work with alpha status).
And then maybe when the feature gets out of alpha, we drop the beta file. What is the k8s compat support rule, one version +/- ?, so we'd only have to keep the beta file around for one release cycle of k8s maybe.

**Comment by egernst** [comment]
we have yaml now.
