### ISSUE TITLE
4.19.X kernel config options

### ISSUE THREAD

**Issue by bryteise** [kata-containers/packaging#406]
The recommended x86_64 default configuration is missing good practice security options.

Things like:
CONFIG_STACKPROTECTOR
CONFIG_X86_INTEL_UMIP
CONFIG_RANDOMIZE_BASE

Improve the overall security posture for the kata kernel. The Clear Linux configuration requires a number of mandatory options making it diverge in places from the recommended configuration. @bwarden has the full list if there is interest in getting closer to the same config.

**Comment by egernst** [comment]
@bryteise thanks for raising.

@bwarden, please share the full list (and rationale if available)?

**Comment by bwarden** [comment]
The list comes from https://github.com/clearlinux/kernel-config-checker/blob/master/kcc/defaults.py

You'd probably need @fenrus75 to comment on the rationale.

**Comment by bwarden** [comment]
More specifically, this is the actual file from which we apply the options:
https://github.com/clearlinux-pkgs/kernel-config/blob/master/mandatory-4.19

**Comment by jodh-intel** [comment]
Nice - that `defaults.py` looks similar to our [hypervisor build config script](https://github.com/kata-containers/packaging/blob/master/scripts/configure-hypervisor.sh#L207) in that it encodes information about the rationale for each option.

@egernst, @grahamwhaley - I appreciate this will slow down #314 landing, but I do feel we should rework this kernel config fragments PR to add this missing detail in terms of one or more optional tags for each option (`m4` ftr! ;) The gory details of the previous discussion: https://github.com/kata-containers/packaging/pull/314#pullrequestreview-195456568.

**Comment by bwarden** [comment]
Feel free to steal from or contribute to the work I've done in https://github.com/clearlinux-pkgs/kernel-config as you implement this :)
