### ISSUE TITLE
kata-deploy: document how to do a local image build

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#413]
Document how to do a local image build of kata-deploy (useful for dev work or making your own local version). We document for the webhook build, so do similar for the deploy.

afaict, the command line is like:

```bash
docker build --build-arg KATA_VER=1.6.0 -t katadocker/kata-deploy:latest .
```

**Comment by grahamwhaley** [comment]
@egernst - is this the sort of line you use?

**Comment by krsna1729** [comment]
That is correct.

**Comment by grahamwhaley** [comment]
A small update.
afaik, this 'local image' build will work if you are running your single k8s node on your single machine - that is, probably having the kubectl on the same machine as your node etc.? I have a minikube kvm single node, so building the image on my host with docker does not inject/pass the new image into the node afaict.
Sooo, I tried to build inside the minikube node, by `s/docker/podman` in the above build line, and it feels like my `podman` is maybe not setup in my node, as I instantly get a `pivot root` type error on the first `RUN` command in the Dockerfile (even if I make that a `mkdir /tmp` for instance).

I think it would be nice if we could detail not only how to build a local image, but how to deploy that image into a remote cluster with kubectl etc., if we can and its not too complex.

**Comment by egernst** [comment]
Well, you'll need to push the image so it is accessible to your nodes.  One example is utilizing DockerHub.

If you want to build your own, you'll also need to have the tarball release (defined by KATA_VER) existing.  We don't build any sources, but simply consume release artifacts, in kata-deploy today.

So... I'm not sure there's a strong use case for building your own?
