### ISSUE TITLE
throttler services should be enabled by default

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#42]
When the user install https://github.com/kata-containers/ksm-throttler, the systemd services should be enabled by default so the packaging 

/cc @grahamwhaley and @chavafg as this could impact CI / metrics if they ever use the distro packages.

**Comment by grahamwhaley** [comment]
@jodh-intel yep, it would impact the metrics CI for sure. I'm presuming there is a nice/easy way to disable the throttler (either by talking directly to the throttler, or we'd do it via systemd), so the day the throttler becomes active by default then we will need to go edit the ksm related code in https://github.com/kata-containers/tests/blob/master/.ci/run_metrics_PR_ci.sh
Should be easy, and generally it is easy to spot when it 'goes wrong', as we end up with a 'double' ksm footprint measure, and no non-ksm measure, and that makes the metrics checks fail :-)
