### ISSUE TITLE
CI: Add job to test OBS package generation

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#480]
To avoid break packages generation on release we should build the packages on packaging changes.

We should find a way to build locally (if time not take a lot) or push a branch in OBS and wait until all is build then test the packages generated.

\cc @marcov  @ganeshmaharaj  @jodh-intel  @grahamwhaley  @egernst

**Comment by jodh-intel** [comment]
@jcvenegas - agreed. I think this is the "other side" of https://github.com/kata-containers/ci/issues/10.

**Comment by jcvenegas** [comment]
@jodh-intel  yeah it should be used by this automation.

**Comment by marcov** [comment]
The most appropriate way would be:
1. build on OBS in a dedicated branch,
2. Test the packages built in step 1.
3. If everything is ok, do a [submit request](https://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.request_and_review_ystem.html#id-1.7.9.5.5.3) from the branch to the official kata project.

**Comment by marcov** [comment]
I am gently bumping this, given the abundance of bug and side effect (at least) I have introduced.

@jcvenegas we should schedule some time to complete this.

**Comment by jcvenegas** [comment]
Agree, I personally feel better to track the work on github but not OBS. Because in that way we dont force kata contributors create a OBS account.

One approach would be create a job that builds kata packages and then test in some distros.

The bad part of this is the time to have the packages ready in a good day packages get ready in 40minutes.

https://dev.azure.com/kata-containers/release-process/_releaseProgress?_a=release-environment-logs&releaseId=15&environmentId=15

Not that build is quick but wait until the packages are published take some time.

I dont know if we can use the osc client to download the packages built   - or check the time that takes to build locally with osc client.
