### ISSUE TITLE
Mirror installation issue

### ISSUE THREAD

**Issue by fredbcode** [kata-containers/packaging#500]
There is something weird with stable branch mirror 

The version installed is alpha not stable
 kata-containers-image 1.7.0~alpha1-20

Not related same bug as #320 with documentation https://github.com/kata-containers/runtime/blob/1.6.3/installation (Error 404) from https://github.com/kata-containers/runtime/releases

**Comment by jcvenegas** [comment]
@fredbcode please try again, fixed manually. #435 was merged after we generated those release notes.

**Comment by jcvenegas** [comment]
aah it is not the same issue sorry.

**Comment by jcvenegas** [comment]
@fredbcode I probably see the potential issue.  what installation method are you using ?

From package installation we ask to set the variable:
```
BRANCH=${the_branch_you want}
```
e.g.
https://github.com/kata-containers/documentation/blob/master/install/debian-installation-guide.md

But I see that we dont mention anything from https://github.com/kata-containers/documentation/tree/master/install#automatic-installation
so we need to update documentation or our script.

**Comment by fredbcode** [comment]
I'm using a source list with "master"  X86_64:/master/xUbuntu_18.04/

**Comment by marcov** [comment]
Hi @fredbcode, thanks for the question, it's good to clarify things.

The way we identify a release version follows the [SEMVER](https://semver.org/) semantic, and the `-alpha` tag is appropriate for packages available in the _master_ branch.

That's because we use the _master_ branch (on OBS) to build packages for the most recently released version. The goal of this branch is to give users the ability to use/experiment with all the latest features added into the _master_ branch of the kata Git repositories.

If you care more about stability over features, we also maintain two stable branches. All this is explained [here](https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md).

(We should probably include this explanation in the documentation if it's not there already @egernst @jodh-intel @jcvenegas)

**Comment by fredbcode** [comment]
@marcov I'm not sure I'm understanding well 

If I'm using the default source list from install documentation (so with master in url X86_64:/master/xUbuntu_18.04/) and type "apt install kata-runtime" I should install the latest 1.7.0 alpha not the latest 1.6.x

I find that rather strange, no ? 

To be more clear:
deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu
_18.04/ /

root@ubuntu-bionic:/# apt-get -y install kata-runtime kata-proxy kata-shim
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  kata-containers-image kata-ksm-throttler kata-linux-container
The following NEW packages will be installed:
  kata-containers-image kata-ksm-throttler kata-linux-container kata-proxy kata-runtime kata-shim
0 upgraded, 6 newly installed, 0 to remove and 168 not upgraded.
Need to get 63.8 MB of archives.
After this operation, 267 MB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_18.04  **kata-containers-image 1.7.0~alpha1-20** [32.0 MB]

**Comment by fredbcode** [comment]
Sorry, I switched 1.6 and 1.7 in my previous post (edited now)

About 404 error in https://github.com/kata-containers/runtime/releases, you can just search "install" and at each url with "blob" there is a 404

**Comment by grahamwhaley** [comment]
@fredbcode - ack on the 404 issue - I think it is only for some releases - like the v1.5.5 install link points to https://github.com/kata-containers/runtime/blob/1.5.5/installation, which is invalid. I suspect we have fixed/changed something recently - @jcvenegas @ganeshmaharaj for input.

**Comment by marcov** [comment]
> If I'm using the default source list from install documentation (so with master in url X86_64:/master/xUbuntu_18.04/) and type "apt install kata-runtime" I should install the latest 1.6.3 not the latest 1.7.x alpha

@fredbcode  Why are you expecting 1.6.3 and not 1.7.x alpha? Is it because there's 1.6.3 at the top of [this](https://github.com/kata-containers/runtime/releases) page?

**Comment by fredbcode** [comment]
Yes,  when I'm reading installation part of  "Release 1.6.3" install 1.7.x alpha is unexpected 

And for me something like:
 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/ **master** /xUbuntu
_18.04/ / -> Stable 1.6

 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/ **alpha** /xUbuntu
_18.04/ / -> 1.7

Is more logical, usually the master branch is for stable release at least for almost all projects I know, but for kata the basic source list is for alpha ? Seems very confusing to me (and perhaps dangerous) 

But maybe Katacontainer is not yet a production ready project ?

**Comment by jcvenegas** [comment]
@fredbcode I see your point, the main issue is that we have  general instructions for any release and if you go and try the installations steps you'll get by default the master branch. Note that master is fine what is the version you are going to get in https://github.com/kata-containers/runtime/blob/master/VERSION 
same for stable releases https://github.com/kata-containers/runtime/blob/stable-1.6/VERSION

I dont see master repository changing what it provides by default. What I can think about is something like a stable repository that give you the latest stable branch. But you may see version changes like 
1.5.5 -> 1.6.0  but still you get the latest stable.  This could work for people using OBS repos, but wee need to know how to provide a similar feature using packageclould  \cc @marcov

**Comment by marcov** [comment]
@jcvenegas On Packagecloud we will provide a single repository link.

- When installing packages in default mode (e.g. `apt-get install kata-runtime`), the _latest_ release version of kata will be installed. _latest_ here means the released version having the greater SEMVER version.

- Users can install _older_ _stable_ versions of packages, _stable_ as explained [here](https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md), and _older_ in the sense that the SEMVER version is less than the _latest_ released one. This will be done using package manager specify syntax, e.g. for the stable branch 1.6 it will be: ` apt-get install kata-runtime=1.6*`

**Comment by jcvenegas** [comment]
@marcov thank for the response, this is similar what we have today. @fredbcode based on this I dont see a short therm solution to have a repository that gives you the latest stable you need to manually.

- By selecting an stable branch for (master will provide rc and alpha updates) like stable-1.5 etc

Lets try to improve the documentation to explain that master repo is going to provide that kind of updates.

**Comment by fredbcode** [comment]
Thanks for the explanations

I disagree, it's not exactly the same, I thought use the latest release and finally I have an alpha (so a dev version) you mean older stable about 1.6, older yes, but the word stable is the point, very confusing and I think finally dangerous.
Marcov I don't know packagecloud but I guess the users are encouraged to use the latest stable release by default, not a dev/alpha version.

I'm working for e2guardian project, default master branch is for stable and users - must - use this version for production.

But we have also specific packages only for testing purposes and debug.

Again thank you it's more clear for me, I will take care of this now.

Sorry I'm writing with my phone ...
