### ISSUE TITLE
README: top level readme could use subsection pointers to build types

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#501]
The packaging repo now holds a number of items and tools, including but not limited to:
- OBS
- kata-deploy
- stable release scripts
- snap stuff

but the top level README in the repo is pretty bare. We could really do with filling out the README with some details for developers about what is available, and how, why and when you use them.

This will also be useful for developers who are trying to track down issues in 'release balls' as well for instance.

/cc @jcvenegas @egernst

**Comment by jodh-intel** [comment]
I'm going to grab this one as it forms part of https://github.com/kata-containers/kata-containers/issues/40.
