### ISSUE TITLE
1.7.0~rc1 kernel missing 9p patch

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#505]
See: https://github.com/kata-containers/tests/issues/1561.

**Comment by chavafg** [comment]
Seems like this is the root cause:
https://build.opensuse.org/package/rdiff/home:katacontainers:releases:x86_64:master/linux-container?linkrev=base&rev=34

@jcvenegas is helping to run a new build.

**Comment by jcvenegas** [comment]
I sent a patch to fix the path to kernel patches. Now they should provide a kernel with patches, @chavafg I suggest wait 1/2 hrs while it is propagated the change in OBS mirrors.
