### ISSUE TITLE
redhat: obs: fail to build runtime

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#510]
Now that 1.7-rc1 is out new packages for Red Hat are failing.

```
[  118s] # github.com/kata-containers/runtime/cli/containerd-shim-kata-v2
[  118s] /home/abuild/rpmbuild/BUILD/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
[  118s] /bin/ld: /tmp/go-link-902220614/000010.o: unrecognized relocation (0x2a) in section `.text'
[  118s] /bin/ld: final link failed: Bad value
[  118s] collect2: error: ld returned 1 exit status
[  118s] 
[  118s] make: *** [/home/abuild/rpmbuild/BUILD/kata-runtime-1.7.0~rc1/containerd-shim-kata-v2] Error 2
[  118s] error: Bad exit status from /var/tmp/rpm-tmp.zADZ3y (%build)
[  118s] 
[  118s] 
[  118s] RPM build errors:
[  118s]     Bad exit status from /var/tmp/rpm-tmp.zADZ3y (%build)
```

In past we have seen a similar error with gcc and golang in ubuntu and was fixed using update repositories for ubnutu 16.04, for Red Hat something similar will be needed.
\cc @egernst @marcov @jodh-intel

**Comment by dagrh** [comment]
Can you give me a bit more context about the build that's failed and what changed from the last version?
Lets see, 'unrecogniszed relocation 0x2a' - the answer to life, the universe and everything:

#define R_386_IRELATIVE    42           /* Adjust indirectly by program base */

so that is defined in my glibc-headers-2.17-155 on my old rhel7.3 ish box - so it's known about for a while.

**Comment by stefanha** [comment]
Aside from making sure you have the latest binutils and gcc, you could also bisect from kata-runtime 1.6 to figure out which commit introduced the issue.  In the very worst case of a toolchain bug that isn't fixed yet, it may be possible to twiddle the code so it doesn't trigger this issue after you've found the relevant commit via git-bisect(1).

**Comment by marcov** [comment]
> In past we have seen a similar error with gcc and golang in ubuntu and was fixed using update repositories for ubnutu 16.04, for Red Hat something similar will be needed.

In that case the issue was a too old version of GCC, preventing the binaries to be built in PIE mode (`go build -buildmode=pie`). However the error here is generated even when building without PIE mode.

**Comment by jodh-intel** [comment]
Do we see the same issue with CentOS? Anyone have the link to the logs? My OBS foo is poor.

**Comment by marcov** [comment]
@jodh-intel: CentOS builds fine.
[RHEL 7 logs](https://build.opensuse.org/build/home:katacontainers:releases:x86_64:master/RHEL_7/x86_64/runtime/_log)
[CentOS logs](https://build.opensuse.org/build/home:katacontainers:releases:x86_64:master/CentOS_7/x86_64/runtime/_log)

**Comment by jodh-intel** [comment]
Thanks @marcov. From the logs:

| distro | gcc version
|-|-|
| CentOS | gcc-4.8.5-36 |
| RHEL | gcc-4.8.2-16 |

**Comment by dagrh** [comment]
that RHEL install is VERY old; it looks like a rhel 7.0, where as the centos is 7.6
$ grep -i binutils /tmp/rhel7 
] [158/228] installing binutils-2.23.52.0.1-16.el7

our system tells me that was 7.0.

**Comment by marcov** [comment]
I tracked this down an incompatibility with go 1.12.3:
- go1.12.3  + {gcc-4.8.2-16, gcc-4.8.5-36}: fails
- go1.11.10  + {gcc-4.8.2-16, gcc-4.8.5-36}: OK

**Comment by jodh-intel** [comment]
Thanks @dagrh.

@marcov - CentOS and RHEL look consistent in https://github.com/kata-containers/packaging/blob/master/obs-packaging/distros, so could there be an issue with RHEL not being updated in OBS?

**Comment by marcov** [comment]
@jodh-intel: the RHEL on OBS is 7.0
I can ask for a newer version to be added, if required.

@dagrh: (in my test setup) using `binutils-2.27-34.base.el7.x86_64.rpm` from CentOS allows to compile with go1.12.4.

**Comment by jodh-intel** [comment]
@marcov - well, I guess we were assuming that "RHEL 7" meant "latest version of RHEL 7". And it appears that "CentOS 7" might indeed mean "latest version of CentOS 7"?

**Comment by jodh-intel** [comment]
There may of course be security implications of building with a static version of any distro...?

**Comment by jodh-intel** [comment]
Related to this and https://github.com/kata-containers/packaging/issues/328, it should like we should consider storing some metadata with each set of release packages on packagecloud that fully describes the build environment for all packages.

**Comment by jodh-intel** [comment]
Confirmed locally that gcc 4.8.5-36 is indeed the newest version of gcc available with CentOS (version 7.6.1810) so it does appear that OBS is updating "CentOS 7", but not RHEL.

**Comment by jodh-intel** [comment]
@marcov - would it be possible to have OBS update RHEL 7 to the latest release (7.6) so that when we specify "RHEL 7" we actually get "RHEL 7.6"?

**Comment by marcov** [comment]
@jodh-intel let me check with the OBS folks.

**Comment by marcov** [comment]
So, there's the `Fedora:EPEL:7` repository we could use, I tried that on a branch, and the can be built.

If you are fine with that, I am going to update the OBS config to use it.

**Comment by dagrh** [comment]
EPEL7 is a different thing again; if we want to test actuall RHEL builds then we just need a newer RHEL.

**Comment by jcvenegas** [comment]
@dagrh  I agree, lets wait for OBS folks response. If this is something that will be updated in short term, lets wait not use EPEL. 

Btw based in last comment we need to think about the usage or not of EPEL in our CI for redhat testing.

https://github.com/kata-containers/tests/blob/master/.ci/setup_env_rhel.sh#L15

```
echo "Add epel repository"
epel_url="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
sudo -E yum install -y "$epel_url"
```

**Comment by marcov** [comment]
Upgrading to a more recent version of RHEL 7 is not going to happen anytime soon. That's why I proposed EPEL. 
@dagrh  what are the problems of building RHEL 7 packages using a build environment based on EPEL7?

**Comment by jcvenegas** [comment]
@dagrh I think the issue is that that is not 100% a Red Hat environment but and old Red Hat  + Packages that are not official from them so we could link things against something that is officially in Red Hat.

**Comment by dagrh** [comment]
Right; I mean it's testing something, but if the purpose is to test a build on RHEL then it wouldn't be doing that. (The CentOS 7.6 is much closer)

**Comment by jcvenegas** [comment]
I'd say the main purpose is to provide a *way for RHEL users to install kata*, and at some point linux distros adopt/integrate it. But yeah providing packages that may link to something that is not officially in RHEL may lead to users to find issues that we dont see.

The real testing actually happens in our CI. While we dont get reported issue that kata does not work as expected , I'd go and enable EPEL just to provide users an installation path using packages . If this is not a good reason to do this we can skip and  push RHEL users to use our static binaries until it is officially integrated. 

@egernst @dagrh what do you think it make more sense?

**Comment by jodh-intel** [comment]
/cc @lsm5.

Related: https://github.com/kata-containers/packaging/issues/6.
