### ISSUE TITLE
Need to revert the patch number to align with deverloper guider doc

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/packaging#527]
Please see :https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#create-a-rootfs-image

$ curl -L https://raw.githubusercontent.com/kata-containers/packaging/master/kernel/patches/4.19.x/0001-NO-UPSTREAM-9P-always-use-cached-inode-to-fill-in-v9.patch | patch -p1
$ curl -L https://raw.githubusercontent.com/kata-containers/packaging/master/kernel/patches/4.19.x/0002-Compile-in-e

You add two patches for virtio-fs and move about two patches number from 0001 & 0002 to 0003* & 0004*, it will make the guide doc error.

Please more sure above patches number to be the same as before.

**Comment by jodh-intel** [comment]
Hi @zhiminghufighting - do you mean this section?

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#create-a-rootfs-image

@jcvenegas, @grahamwhaley - Why can't we drop the entire block of shell commands in the section above and replace it with a call to [`build-kernel.sh`](https://github.com/kata-containers/packaging/blob/master/kernel/build-kernel.sh)? That would avoid breakage like this I think?

**Comment by grahamwhaley** [comment]
I think the `curl .... v9.patch` mentions are in the `install guest kernel images` section - they are scrolled off the rhs of the code block:
https://github.com/kata-containers/documentation/blob/95af6edb1abab772f47281e2b091285d1d24b9aa/Developer-Guide.md#install-guest-kernel-images

Yes, I agree, that block can probably be re-worked much more succinctly by using the `build-kernel.sh` script - @jcvenegas , if you agree, can you update that?

**Comment by grahamwhaley** [comment]
In the meantime @zhiminghufighting - I believe there are better kernel build instructions over in the packaging repo at: https://github.com/kata-containers/packaging/tree/master/kernel :-)

**Comment by zhiminghufighting** [comment]
@jodh-intel @grahamwhaley  totally agree to move the build instructions into a build-kernel.sh.
But there shouldn't be conflictions in descriptions between the guide doc and actually patches names.

**Comment by zhiminghufighting** [comment]
Suggest to redirect the "build guest kernel" to a unified method.

**Comment by grahamwhaley** [comment]
Hi @zhiminghufighting - the `build-kernel.sh` script already exists: https://github.com/kata-containers/packaging/blob/master/kernel/build-kernel.sh
We just need the documents updated to reference that instead of listing the steps in detail :-)
