### ISSUE TITLE
Missing Arm64 guest kernel config file

### ISSUE THREAD

**Issue by Weichen81** [kata-containers/packaging#53]
As the [Developer-Guide](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md)[1] mentioned, the progress of installing guest kernel images need a default kernel config file. But for Arm64 architecture, this config file is missing.  In this case, the Arm64 users can't follow the guide to complete the installation of guest kernel.

**Comment by chavafg** [comment]
we already provide arm64 config files on https://github.com/kata-containers/packaging/tree/master/kernel/configs
