### ISSUE TITLE
CONFIG_X86_PMEM_LEGACY not need for NVDIMM emulation with QEMU

### ISSUE THREAD

**Issue by marcov** [kata-containers/packaging#562]
Support for legacy  e820 PMEM can be dropped in the x86 kernel configs. That's not needed when using QEMU vNVDIMM.
References:
https://code.woboq.org/linux/linux/arch/x86/include/uapi/asm/e820.h.html#39

----
/cc @stefanha @devimc

**Comment by stefanha** [comment]
@marcov Yes, I think we can rely purely on ACPI NFIT.  e820 pmem is not needed.
