### ISSUE TITLE
RPM packages dependencies should not include the release number

### ISSUE THREAD

**Issue by marcov** [kata-containers/packaging#563]
Recently [we added to DEB packages strict dependency check](https://github.com/kata-containers/packaging/pull/532), by specifying `Depends: 
 package = version-release`.

However, this had the side effect of breaking RPM packages dependency. That's because, for RPM (but not for DEBs), OBS is managing the Release number value by itself, instead of using what's specified in the spec files. So, you can't rely on what's in the spec file to specify a dependency, as the package built using it will have a different release number.

Since RPMs allow specifying strict dependencies without a Release number, we can fix this by omitting the release number just for these.

---
/cc @jcvenegas @egernst @ganeshmaharaj

**Comment by jcvenegas** [comment]
Yeah this make sense, I updated manually  the 1.6 packages with this approach and seems to work well.
