### ISSUE TITLE
Debug(info) packages

### ISSUE THREAD

**Issue by dagrh** [kata-containers/packaging#573]
It would be useful to have debug builds (or debuginfo depending on the distro) packages for each of the kata packages.  e.g. when debugging a hang or seg.

**Comment by grahamwhaley** [comment]
/cc @marcov @jcvenegas 
Let's at least discuss what it would take - I presume there are some well trodden standard ways to extract and package that information :-)

**Comment by marcov** [comment]
It should be enough to enable the DebugInfo builds in the OBS UI 
OR (equivalently)
adding to `osc meta -e prj`:
```
  <debuginfo>
    <enable/>
  </debuginfo>
```
