### ISSUE TITLE
configuration-qemu.toml specifies image= and initrd=

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#574]
# Description of problem

The `configuration-qemu.toml` file in the `kata-runtime` package specifies:

```
initrd = "/usr/share/kata-containers/kata-containers-initrd.img"
image = "/usr/share/kata-containers/kata-containers.img"
```

# Expected result

Only one of `initrd=` or `image=` can be specified - both is an error.

# Actual result

The `image=` option should be specified and the `initrd=` should not be present in the file (or commented out).

However, oddly (and thankfully) this does not cause an issue because of another problem:

```sh
$ ls -l /usr/share/defaults/kata-containers 
total 80
-rw-r--r-- 1 root root 13018 Jun 13 11:51 configuration-acrn.toml
-rw-r--r-- 1 root root 12647 Jun 12 05:55 configuration-fc.toml
-rw-r--r-- 1 root root 15290 Jun 12 05:55 configuration-nemu.toml
-rw-r--r-- 1 root root 15639 Jun 12 05:55 configuration-qemu.toml
-rw-r--r-- 1 root root 15574 Jun 12 05:55 configuration.toml
```

That looks wrong to me - `configuration.toml` should be a link to `configuration-qemu.toml`.

The default configuration file `configuration.toml` is in fact different to `configuration-qemu.toml`:

```diff
$ diff /usr/share/defaults/kata-containers/configuration.toml /usr/share/defaults/kata-containers/configuration-qemu.toml
15a16
> initrd = "/usr/share/kata-containers/kata-containers-initrd.img"
```
In English: `configuration.toml` only defines `image=`, which is valid.

/cc @jcvenegas, @marcov.

**Comment by jodh-intel** [comment]
This is in `kata-runtime` package version `1.8.0~alpha1-36` btw.

**Comment by marcov** [comment]
Interesting.

- About having both `image=` and `initrd=` in configuration-qemu.toml: that comes from what's installed with runtime's `make install`, so it should IMO be corrected there.

- About configuration.toml not being a symlink:  can be fixed adding `--follow-symlinks` to the currenct sed command line that is `sed -i -e '/^initrd =/d' %{buildroot}/usr/share/defaults/kata-containers/configuration.toml`. But, the sed command could be suppressed all together if `make install` only specify an image or a initrd.
