### ISSUE TITLE
Distribution support for Kata Containers packaging

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#6]
Need to come up with list of distributions that should be supported for Kata's packaging.

**Comment by grahamwhaley** [comment]
As mentioned in the conf call, the obvious bases are:

 - Debian
 - Fedora

but, we have also found that for the various distros then further derived from these, we have found build and install differences.

The base list we use for Clear Containers is (in no particular order - but maybe we should order this in some sort of priority/preference as I don't think we will manage to implement them all at once and in parallel):

 - Fedora
 - Ubuntu
 - SuSe
 - RHEL
 - CentOS
 
Others we should then consider are possibly:
 - Clear Linux
 - EulerOS

as we have some intergration work for those already on-going.

**Comment by jodh-intel** [comment]
The Clear Containers wiki page I was thinking of was actually about how we handle updating the list of supported distro *versions*:

- https://github.com/clearcontainers/runtime/wiki/Handling-new-and-end-of-life-distro-versions

A couple of other considerations:

- We need to specify the list of architectures for each distro we're planning to provide packages for (consider that Debian supports 20+ architectures...).

- If we're going to provide packages for a distro/version/architecture triplet, we need to test them. That implies we need a CI capability for every distro/version/architecture triplet.

Question:

- How are we going to handle those (important) distros that cannot be automatically tested due to licensing / setup issues (such as RHEL - https://github.com/clearcontainers/runtime/blob/master/installation/rhel-setup.sh)?

/cc @GabyCT.

**Comment by grahamwhaley** [comment]
We might be able to swing the RHEL stuff via their free developer program:
https://developers.redhat.com/products/rhel/download/

**Comment by egernst** [comment]
@grahamwhaley @jodh-intel I initiated some discussion with Melvin Hillsman from openstack regarding RHEL.  I opened an issue in the CI repo to track this:  https://github.com/kata-containers/ci/issues/3

Is this the only reason we obtained a docker EE license?

**Comment by grahamwhaley** [comment]
@jodh-intel @GabyCT - do you remember the details about EE and RHEL - was it that RHEL only support docker-EE, and not the CE version (or something like that iirc)?
If so, I guess even if we can use the developer program for RHEL access, we may still need to purchase a docker-EE license. I had a look to see if there was a docker-EE dev program, but I could not see one. We can always ask first though :-)

**Comment by mrguitar** [comment]
@grahamwhaley, Red Hat supports the version of docker that's included with RHEL in the Extras repo. If you have a registered system you can run something like: 
subscription-manager repos --enable=rhel-7-server-extras-rpms && yum -y install docker && systemctl enable --now docker

**Comment by jodh-intel** [comment]
Thanks for the information @mrguitar. I've raised https://github.com/clearcontainers/runtime/issues/1016 to allow us to update the Clear Containers RHEL install script as a start.

**Comment by jodh-intel** [comment]
Summarising everything I can find related to native packaging:

| Distro | Status | Contacts | Details | URLs |
|-|-|-|-|-|
| ClearLinux | complete | @bryteise | | https://github.com/clearlinux-pkgs?utf8=%E2%9C%93&q=kata&type=&language= |
| Ubuntu | complete | @devimc | Snap packaging | https://snapcraft.io/kata-containers |
| SuSE | in progress | @marco, @mssola, @flavio | Currently evolving the existing OBS packaging (refining and simplifying to make to make it more suitable for SuSE and other distros) | |
| Fedora | in progress | @jcvenegas, @lsm5 | | https://bugzilla.redhat.com/show_bug.cgi?id=1590425 https://fedoraproject.org/PackageReviewStatus/NEW.html https://copr.fedorainfracloud.org/coprs/jcvenegas/kata/ |
| RHEL | blocked? |  @lsm5? | Waiting outcome of Fedora packaging? | |
| CentOS | blocked |  | Blocked on RHEL packaging | |
| EulerOS | blocked | @liangchenye? | Blocked on CentOS packaging | |
| Debian | ? | ? | Need Debian packager and Debian Developer sponsor | |

# Debian packaging

We already use Debian + Ubuntu (DEB) packaging for our OBS packages, for example:

- https://github.com/kata-containers/packaging/tree/master/obs-packaging/runtime

However, to have Kata packages available in Debian's repositories will require more work. If anyone has the skills and time and wishes to volunteer to help out, please let us know! :smile:

/cc @egernst, @ttx.

**Comment by lsm5** [comment]
Re: RHEL, yup, once things are working in Fedora, @fatherlinux and @mrguitar can probably take it from there.

**Comment by jodh-intel** [comment]
Thanks @lsm5 - table updated.

**Comment by flavio** [comment]
@jodh-intel a minor note, for openSUSE/SUSE it's not `<at>marco`, but @marcov

**Comment by jodh-intel** [comment]
@flavio - thanks - updated! :smile:

**Comment by jodh-intel** [comment]
@mssola, @flavio, @lsm5, @jcvenegas - any update on the SuSE / Fedora packaging efforts that I can add to the table above? A couple of questions for you all:

- Do you have a feel for the % complete for example?
- Are you facing any blockers we can help with?

**Comment by jodh-intel** [comment]
@marcov, @mssola, @flavio, @lsm5, @jcvenegas - any further updates on SuSE / RHEL / Fedora packaging for the table above?

**Comment by jodh-intel** [comment]
Hi @marcov, @lsm5 - it would be great if you could provide an update on the current packaging status and any blockers for SuSE/Fedora respectively.

**Comment by marcov** [comment]
Hi @jodh-intel, from my side I plan in the short term to resume the work of making my flavour of Kata packages {[available here](https://build.opensuse.org/project/show/devel:kubic:katacontainers), [and here](https://build.opensuse.org/project/show/devel:kubic:katacontainers:images)} something that can be integrated into the official openSUSE repos. 
I am using these packages already on my x86_64 host, and tested successfully the aarch64 version. There are some errors building for ppc and s390x kernels that need  to be sorted out.
Note that I am going to drop non-SUSE distributions from this repo soon, as I could understand that packing for other distros will be done separately.

The possible blockers I see is with the acceptance of qemu-lite and the kernel packages into the offical openSUSE repos, I dont know yet it that would be OK to have custom versions of qemu and kernel. But at least for the kernel we are going to find a way.

**Comment by egernst** [comment]
stale

**Comment by jodh-intel** [comment]
Re-opening as this isn't resolved (but needs to be ;)

**Comment by c3d** [comment]
Hi @jodh-intel. I'm currently working on kata-runtime and other packages for Fedora. I started with the work done by @lsm5, but I expect to be doing more of the heavy lifting from now on. Please feel free to add me to your table. Copr build for 1.8.0 here, currently building 1.7.3: https://copr.fedorainfracloud.org/coprs/ddd/kata

**Comment by marcov** [comment]
@jodh-intel can you make [this table](https://github.com/kata-containers/packaging/issues/6#issuecomment-453940053) a wiki page, so that people can update it?

**Comment by grahamwhaley** [comment]
I'd vote for a doc or wiki page, as I think they are substantially easier to find than Issues (I even struggle to find my own docs when they are buried in Issues).

**Comment by jodh-intel** [comment]
For the future, all. you need to do is copy/paste my comment with the table above into a new wiki page. Anyway, here it is:

- https://github.com/kata-containers/packaging/wiki/Distro-packaging-status

@c3d - Great! I've added you to the table in the wiki link.

If folk have trouble editing the wiki, let us know.

**Comment by marcov** [comment]
awesome, thank you @jodh-intel, nice status icons btw :stuck_out_tongue:
