### ISSUE TITLE
qemu-vanilla isn't an awesome name

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#602]
see the thread here: https://github.com/kata-containers/packaging/pull/580#pullrequestreview-250337925

Storing a kata specific build of QEMU shouldn't require a unique name, just a unique path?

**Comment by jodh-intel** [comment]
... aaaaaaand even though it's only Monday, I think it's safe to award the "Best issue title of the week" :1st_place_medal: to @egernst!

Agreed - if we stick everything in a Kata-specific directory, we can "namespace" it off from other qemu's on the system.

**Comment by jodh-intel** [comment]
... anyhow I always preferred `qemu-rum-and-raisin` personally...
