### ISSUE TITLE
VM templating does not work on master

### ISSUE THREAD

**Issue by ganeshmaharaj** [kata-containers/packaging#642]
VM templating is not working with master anymore.

`kata-runtime factory init` will fail.
# Expected result
Command returns `vm factory initialized`

#Actual Result
`QMP command failed: Invalid parameter 'bypass-shared-memory'`

**Comment by bergwolf** [comment]
The problem is that #641 depends on kata-containers/runtime/pull#1799 but was merged before the runtime PR.

I've just merged kata-containers/runtime#1799 and the issue should be gone.
