### ISSUE TITLE
Add a script to configure docker for static version of Kata

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#648]
To simplify https://github.com/kata-containers/documentation/issues/470, we need a script inside the `kata-static-${version}-${arch}.tar.xz` file that can be referenced by an installation guide. This script will configure `/etc/docker/daemon.json`. We *could* simply add the shell code to such an install doc, but having a script means:

- There is less for the user to type potentially.
- The script can deal with distro-specifics (meaning we only need a single "how to install the static version of Kata" doc).

**Comment by grahamwhaley** [comment]
We might want to check for overlap on kata-deploy here as well, as afaik that probably has some scripting already to install/configure docker. And, there are known niggles there I think as you can configure docker in two different files/ways, but not both - and iirc, our packages do it one way and our kata-deploy the other - so if you try to install both, they clash....

**Comment by jodh-intel** [comment]
@grahamwhaley - good point.

@egernst - can we rip the guts out of kata-deploy into a script? afaics, kata-deploy assumes the static archive has already been unpacked. But I think we need a script stored *inside* the archive to allow docker to be configured since:

- Users may have no knowledge of / should not need to know about kata-deploy - they just want to download the static archive and get going with minimal fuss.
- kata-deploy can then be simplified to call the script inside the archive.

**Comment by jodh-intel** [comment]
`echo "can we rip the guts out of" | sed 's/we/i/g'`

**Comment by jodh-intel** [comment]
Ping @egernst, @jcvenegas.
