### ISSUE TITLE
snap: ppc/arm/s390x: can't run containers because of clearlinux rootfs

### ISSUE THREAD

**Issue by devimc** [kata-containers/packaging#678]
With the rootfs image kata shows better numbers in x86_64, is the same in other architectures?
see https://github.com/kata-containers/packaging/pull/668

cc @nitkon @Pennyzct @alicefr @tuan-hoang1

**Comment by nitkon** [comment]
@devimc : Clearlinux and image rootfs are not supported on Power yet.

**Comment by devimc** [comment]
@nitkon is initrd the best option for ppc ?

**Comment by alicefr** [comment]
@devimc I need to check. What have you used to measure the performance?

**Comment by nitkon** [comment]
@devimc: Yes initrd would be the best.

**Comment by devimc** [comment]
@alicefr 

see https://github.com/kata-containers/tests/tree/master/metrics and https://github.com/kata-containers/packaging/pull/668#issuecomment-521711784

the following commands will generate the results in the `results` directory, you have to move all the `.json` files into a subdirectory (`results/img`) before running the next test (`results/initrd`)

```sh
echo 0 | sudo tee /sys/kernel/mm/ksm/run && \
bash time/launch_times.sh -i debian -n 50 && \
bash density/docker_memory_usage.sh 50 120 no && \
echo 1 | sudo tee /sys/kernel/mm/ksm/run && \
bash density/docker_memory_usage.sh 50 120 yes
```

**Comment by devimc** [comment]
@alicefr to generate the report run `./report/makereport.sh`

**Comment by Pennyzct** [comment]
Hi @devimc thanks for the notification. ;)
I will take one long holiday from next day to the end of Aug. During the time, @justin-he @jongwu will be my back-up and will do the metrics between rootfs and initrd. ;)

**Comment by jodh-intel** [comment]
Enjoy your holiday @Pennyzct! :sunglasses:

**Comment by grahamwhaley** [comment]
fyi  @justin-he @jongwu  - I've updated the table at
https://github.com/kata-containers/community/wiki/Areas-of-interest
to add you both as ARM aware folks.... so we can locate you if need be ;-)

**Comment by jongwu** [comment]
@grahamwhaley  ok, thanks

**Comment by jongwu** [comment]
@devimc  I get the boot up time metric result on arm64, it seems image is better than initrd.

**Comment by devimc** [comment]
@jongwu great! , which distro did you use in your test?

Arch | Good performance with
------------ | -------------
x86_64 | image
arm | image
ppc | initrd
s390x |

**Comment by jongwu** [comment]
@devimc 
> @jongwu great! , which distro did you use in your test?
debian, just the command line you offered above.

**Comment by jongwu** [comment]
@devimc  debian, I use the command line you offered above.
