### ISSUE TITLE
packaging test in CI hangs more than 20 minutes in docker build

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#72]
The packages in CI are build using a dockerfile the dockerfile takes more than 20 minutes in a single installation step. We need to find out the rootcause why is takaing a long time and re-enable tests.

**Comment by jcvenegas** [comment]
I tried locally and it is working. The problem seems that only happen in the CI VMs. 

It is when the Dockerfile to install `osc` tries to pull metadata from suse servers.

It even hangs running:
`RUN zypper -v -n ref`

Here the output:
```
Step 5/15 : RUN zypper -v -n ref
 ---> Running in 6eb08e539120
Verbosity: 1
Entering non-interactive mode.
Initializing Target
Specified repositories: 
Checking whether to refresh metadata for NON OSS
Retrieving repository 'NON OSS' metadata [.Retrieving: media [not found]
Retrieving: repomd.xml.asc [..done]
```

**Comment by grahamwhaley** [comment]
Hmm. My gut instinct shouts 'proxy' something, but I wonder if this might be to do with the http/https re-direction - that was on SuSe was it @jodh-intel ?
