### ISSUE TITLE
wrong script name for virtiofs qemu static build

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#725]
kata-deploy-binaries calls incorrect script name for qemu-virtiofs:

https://github.com/kata-containers/packaging/blob/master/release/kata-deploy-binaries.sh#L125

**Comment by GabyCT** [comment]
@egernst this is fixed at https://github.com/kata-containers/packaging/pull/710/files#diff-cda56217d1705e801a5f774f2d37126cR136

**Comment by egernst** [comment]
you are FAST!  Okay -- I noticed while going through release handling for 1.8.2/1.9.0-alpha2.

@jcvenegas -- heads up --  this is another case where we really should be using stable branches for packaging.

**Comment by jcvenegas** [comment]
@egernst agree, for that case it would be just broken for 1.0.0-alpha0 but no 1.8.2  - btw this also tell us we need some testing for static binaries in the CI.
