### ISSUE TITLE
Publish default kernel headers?

### ISSUE THREAD

**Issue by artem-nefedov** [kata-containers/packaging#738]
I want to try using kata-containers as a platform to test kernel modules.
This would be much simpler if kernel headers for default were published (as Jenkins artifacts?).
Currently, I would have to setup build myself just to generate necessary headers, so I can build my module against it.

**Comment by devimc** [comment]
cc @jcvenegas @egernst

**Comment by jcvenegas** [comment]
@artem-nefedov we could add them as part of our cache kernel job, but I think you are using latest kata releases so probably could be added into our kata-static tarball.

**Comment by artem-nefedov** [comment]
@jcvenegas that seems like a good idea
