### ISSUE TITLE
kernel: config: Improve CI for kernel config changes

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/packaging#78]
There is two part in this issue.

__Keep kernel config in sync__
We need to maintain the kernel configs consistent between each other (across architectures) because we already have some discrepancies about some components that are not architecture specific. I am not sure how we can maintain some sort of synchronization across archs and which tool already exist for this, but we need this if we want to make sure we'll have Kata working consistently across x86, ARM and PPC.

__Validate kernel config changes__
We need the CI to run some specific check when modification are done to the `kernel/config` directory. This means every time a config gets modified, it should try to build the kernel with this config and then recreate an image to perform a sanity check (or maybe the full CI ???) that Kata Containers still work as expected. And to go one step further, we would need specific CI jobs to trigger the same tests for ARM and PPC configs on the appropriate worker VMs, so that we try on the appropriate arch. Maybe a simple way to bypass the complexity of having several worker VMs with different architectures would be to use cross compilation (but this means we can only try the build, we couldn't test Kata after this).

/cc @jodh-intel

**Comment by jodh-intel** [comment]
Thanks for raising this @sboeuf!

## Keep kernel config in sync

+1.

As mentioned on https://github.com/kata-containers/osbuilder/issues/6, I've been digging around a bit and comparing the kernel configs and they do not appear to be consistent. For example, wouldn't we expect the following three values to be identical?

```
$ cd $GOPATH/src/github.com/kata-containers/packaging
$ for config in kernel/configs/*.x; do grep ^CONFIG "$config"|grep CONFIG_ARCH|sort -u|wc -l;done
37
49
62
```

What we need is for a kernel expert to pick over the three config files and work out:

- Which configs are missing key features

  aka: platform-inconsistency - running a container on platform X fails on platform Y).

- which configs have "unnecessary" features enabled

  aka: bloat, boot speed and security considerations.

/cc @bergwolf, @gnawux, @egernst, @grahamwhaley, @annabellebertooch, @brecky777.

Related:

- https://github.com/kata-containers/community/wiki/Document-essential-kernel-config-options-for-ppc64le,-arm64-and-x86_64.
- https://github.com/kata-containers/packaging/issues/8
- https://github.com/kata-containers/packaging/issues/55
- https://github.com/kata-containers/packaging/issues/56

## Validate kernel config changes

+1.

The question is how realistic is it that we'll be able to re-test the kernel build for all three architectures if a file in `kernel/configs/` changes? Would zuul be able to support our three architectures (x86_64, arm64, ppc64le) @mnaser, and @cboylan?

/cc @Pennyzct, @Weichen81, @nitkon, @harche.
