### ISSUE TITLE
crio.runtime.runtimes.kata-qemu-virtiofs set incorrectly in /etc/crio/crio.conf 

### ISSUE THREAD

**Issue by lauatic** [kata-containers/packaging#780]
# Description of problem
In the kata-deploy/scripts/kata-deploy.sh script, the kata_qemu_virtiofs_conf uses header. 
[$kata_qemu_conf]
  runtime_path = "${kata_qemu_virtiofs_path}"
It should be
[$kata_qemu_virtiofs_conf]
  runtime_path = "${kata_qemu_virtiofs_path}"

(replace this text with the list of steps you followed)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by lauatic** [comment]
I have tested the change and can submit the code change for review.

**Comment by grahamwhaley** [comment]
this is ringing a :bell: - @chavafg , did you fix this already this week?

**Comment by lauatic** [comment]
The issue was fixed in https://github.com/kata-containers/packaging/issues/771
