### ISSUE TITLE
runtime_type in /etc/crio/crio.conf file for kata runtimes

### ISSUE THREAD

**Issue by lauatic** [kata-containers/packaging#781]
# Description of problem
kata-deloy/scripts/kata-deploy.sh does not include the runtime_type in the /etc/crio/crio.conf.  What should the runtime_type for kata runtime be?  I tried with runtime_type="oci" and runtime_type="vm" and that did not work.

Do I need to set the runtime_root also?

[crio.runtime.runtimes.kata-qemu]
runtime_path = "/opt/kata/bin/kata-qemu"
runtime_type = "???"
runtime_root = "???"

(replace this text with the list of steps you followed)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by grahamwhaley** [comment]
I'm going to guess, if `runtime_type` does not get set, then it is either not needed or the default works, as `kata-deploy` works with k8s and kata :-) If you have a reference to the crio conf docs that talk about `runtime_type` that would help. Also, what version(s) of crio/k8s/kata are you using.

/cc @egernst @amshinde in case they know.

**Comment by lauatic** [comment]
$ /opt/kata/bin/kata-runtime version 
kata-runtime  : 1.8.2
   commit   : 5ab950d36302127d38765088495306fa282842fa
   OCI specs: 1.0.1-dev
# crio --version 
crio version 1.15.2-dev
