### ISSUE TITLE
Is /opt/kata/bin/containerd-shim-kata-v2 supported in /etc/crio/crio.conf

### ISSUE THREAD

**Issue by lauatic** [kata-containers/packaging#782]
# Description of problem
I want to use the shimv2 and am trying this config in the /etc/crio/crio.conf file.  Is this supported?
[crio.runtime.runtimes.kata-shimv2]
runtime_path = "/opt/kata/bin/containerd-shim-kata-v2"
runtime_type = "???"
runtime_root = "???"

If it is supported, I want to this issue to add the lines to the packaging/kata-deploy/scripts/kata-deploy.sh:configure_crio().

(replace this text with the list of steps you followed)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by lauatic** [comment]
I can work on this issue and submit the code change if shimv2 is a supported configuration in /etc/crio/crio.conf file.

**Comment by grahamwhaley** [comment]
I'm not sure if these are required fields for `kata` to work with containerd/shimv2 - does the document https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#configuration help at all?
@gnawux - can you clarify?

**Comment by lauatic** [comment]
This issue is fro crio.  In the /etc/crio/crio.conf file, I want to know the syntax for configuring the shimv2.

**Comment by lauatic** [comment]
I think the information on https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#configuration is for configuring the /etc/containerd/config.toml file to work with containerd.  Is this right?

**Comment by lauatic** [comment]
In my test environment, the /etc/containerd/config.toml has the cri plugins.  Do the plugins look right?

[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
      no_pivot = false
    [plugins.cri.containerd.runtimes]
      [plugins.cri.containerd.runtimes.runc]
         runtime_type = "io.containerd.runc.v1"
         [plugins.cri.containerd.runtimes.runc.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "runc"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false
      [plugins.cri.containerd.runtimes.kata]
         runtime_type = "io.containerd.kata.v2"
	 [plugins.cri.containerd.runtimes.kata.options]
	   ConfigPath = "/etc/kata-containers/configuration.toml"
      [plugins.cri.containerd.runtimes.katacli]
         runtime_type = "io.containerd.runc.v1"
         [plugins.cri.containerd.runtimes.katacli.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "/usr/bin/kata-runtime"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false

To start shimv2, from the CLI, I have to use this runtime name.
sudo ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest kata-hello sh

To start runc, from the CLI, I have to use this runtime name.
sudo ctr run --runtime io.containerd.runtime.v1.linux -t -rm docker.io/library/busybox:latest runc-hello sh

I have yet to find the right runtime name to use for kata v1 runtime.  Is it io.containerd.run.kata.v1
