### ISSUE TITLE
releases of kata-deploy should install the corresponding kata-container release

### ISSUE THREAD

**Issue by pohly** [kata-containers/packaging#826]
**Which feature do you think can be improved?**

`kubectl apply -f kata-deploy.yaml`

My expectation was that by checking out a certain release of `packaging`, I would get the installation files which install the corresponding kata-containers release. That's not the case for the current latest release (1.9.1):
https://github.com/kata-containers/packaging/blob/1.9.1/kata-deploy/kata-deploy.yaml#L19

That installs the katadocker/kata-deploy:latest image which may or may not contain 1.9.1. Currently it does, but for how long?

**How can it be improved?**

The .yaml file should reference katadocker/kata-deploy:1.9.1.

**Comment by pohly** [comment]
Note that a similar issue exists for the `Install Kata and configure Docker` command line. If people just cut-and-paste, they might unintentionally install "latest" if they don't append the desired version first. But at least here users have it right in front of them. With the .yaml file it is more hidden.

**Comment by pohly** [comment]
Another solution would be a wrapper script that patches in the desired image version on-the-fly. I like that less than providing a proper .yaml because with a .yaml that already has the right content, one can do `kubectl create -f https://github.com/kata-containers/packaging/raw/1.9.1/kata-deploy/kata-deploy.yaml` without checking out the repo.

**Comment by egernst** [comment]
I think we could improve the documentation to clarify this behavior, but it is yaml, and it should just install the latest, imo.  Users can always modify the yaml to lock down to a particular release version (ie, they are still kept on dockerhub).

What do others think?
