### ISSUE TITLE
kata-deploy.sh: warn about unsupported runtime

### ISSUE THREAD

**Issue by pohly** [kata-containers/packaging#827]
**Which feature do you think can be improved?**

I deployed kata-deploy.yaml on a Kubernetes cluster with `Container Runtime Version: docker://<some version - don't remember>`. When that didn't put into /opt/kata on the host, I started checking the container status and logs of the daemon set - nothing, container is healthy and the log empty.

After I ran the script manually with `bash -x` it became clear that it went straight to `sleep infinity` because that runtime isn't supported.

**How can it be improved?**

Print an error to `/dev/termination-log` (https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#writing-and-reading-a-termination-message), then exit with an error. That should make the problem visible via `kubectl`. I'm just not exactly sure how that will interact with the daemonset, though. If all failed pods get killed without propagating the error up to the daemonset, we gain nothing. Needs to be tested...

If that part doesn't work, then at least log the error in the normal output before sleeping.

**Additional Information**

Tried with 1.9.1.

**Comment by egernst** [comment]
Thanks @pohly .  

We can't just exit, as this is a daemonset, and we'd hit a constant crash loop. Is there anything in the particular pods' log?

**Comment by pohly** [comment]
> We can't just exit, as this is a daemonset, and we'd hit a constant crash loop.

Which wouldn't necessary be a bad thing, would it? Kata Containers is not going to work in this cluster, the sooner the admin learns about that the better.

> Is there anything in the particular pods' log?

No, nothing. The script goes straight to sleep, without any output.

**Comment by egernst** [comment]
To clarify, that *node* will not work with Kata.  Its possible you have a heterogenous cluster, with respect to CRI-implementations.
