### ISSUE TITLE
kata-deploy for containerd does not use fully qualified v2 annotation

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/packaging#881]
# Description of problem

When `kata-deploy` is used with containerd and a `/etc/containerd/config` is created, it populates using the annotation `[plugins.cri.containerd.runtimes.kata]`   However, according to the v2 containerd [config ](https://github.com/containerd/cri/blob/master/docs/config.md) the annotation should be `[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata] `   The first config does work for me on Clear Linux with containerd v1.3 but others have reported the longer annotation is needed for containerd v1.3 and that shorter annotation did not work for them.

**Comment by egernst** [comment]
Using the full path for the plugin makes sense to me. We could use help with a PR to update this!

**Comment by dsyer** [comment]
You could detect the version from the TOML (v2 config files have "version = 2" on line 1). This is definitely a showstopper for using kata with such a system (seems to be the default in recent versions of containerd). I was able to get it working by manually patching the config file and restarting containerd:

```
$ sed -i -e 's/plugins.cri/plugins."io.containerd.grpc.v1.cri"/' /etc/containerd/config.toml
$ systemctl restart containerd
```

but obviously that is a bit crap.

**Comment by grahamwhaley** [comment]
Thanks @dsyer - I don't suppose you have the time and inclination to make a PR with that change do you? :-)

**Comment by dsyer** [comment]
There you go. It's only tested manually by me. Feel free to incorporate that change if you can.
