### ISSUE TITLE
Build all go packages using same go version as CI

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#9]
We need to ensure that when building golang packages we use the standard go version defined in the versions database.

Once https://github.com/kata-containers/runtime/pull/114 lands, this will be queryable using:

```
$ go get -d github.com/kata-containers/runtime
$ cd $GOPATH/src/github.com/kata-containers/runtime
$ go get github.com/mikefarah/yq
$ yq read versions.yaml languages.golang.version
1.8.3
```

Related:

- #1
- https://github.com/clearcontainers/packaging/issues/257

**Comment by egernst** [comment]
@erick0z  - PTAL?  I see the queryability is available now (114 is merged).

**Comment by erick0z** [comment]
@egernst Will do

**Comment by devimc** [comment]
we use the `versions.yaml` in all the repositories, the last one in support it was osbuilder
