### ISSUE TITLE
obs packages missing for ubuntu 19.04

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/packaging#919]
Obs packages are missing for ubuntu 19.04,
```
[91mE[0m[91m: Unable to locate package kata-runtime
E: Unable to locate package kata-proxy
E: Unable to locate package kata-shim
[0mThe command '/bin/sh -c cd "/home/tests" && ./cmd/kata-manager/kata-manager.sh install-packages' returned a non-zero code: 100
```
See http://jenkins.katacontainers.io/job/obs-package-release/35/console
/cc @jcvenegas

**Comment by rhafer** [comment]
According to https://build.opensuse.org/project/monitor/home:katacontainers:releases:x86_64:master?utf8=%E2%9C%93&defaults=0&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&arch_x86_64=1&repo_xUbuntu_19_04=1
those packages currently have some issue with their build dependencies:

`have choice for fakeroot needed by devscripts: fakeroot pseudo`

**Comment by GabyCT** [comment]
That is weird @rhafer as `fakeroot` is part of the dependencies
https://github.com/kata-containers/packaging/blob/a878afb7c306638f73b60cfa9a0e8f70cd60f2ea/obs-packaging/runtime/kata-runtime.dsc-template#L10

**Comment by jcvenegas** [comment]
we have not releases for master yet, last releases where for the last two stable branches. For the next release in master that should be included.

**Comment by rhafer** [comment]
An alternative fix cloud be to adjust the OBS project configuration to prefer "fakeroot" over "pseudo". Buy yeah, explicitly requesting fakeroot via "Build-Depends" should do it as well.

**Comment by GabyCT** [comment]
Closing this issue as we not longer support ubuntu 19.04
