### ISSUE TITLE
.img file size growth between v1.0.0 and v1.1.0

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#93]
It appears that our .img file footprint has grown between the 1.0.0 and 1.1.0 releases.
I noticed this when looking at some footprints from the [docker test](https://github.com/kata-containers/tests/blob/master/metrics/density/docker_memory_usage.sh). Grabbing some numbers from some a shim PR being built before/after the tagging of 1.1.0 (I just happened to have the data to hand)... (in Kb)

| What | 1.0.0 | 1.1.0 |
| ---- | ---- | ---- |
| noKSM | 122803 | 138572 |
| KSM | 46047 | 45590 |

We can see the no-KSM footprint has bumped ~13%.
I dug into the logs a bit, and in the Jenkins logs found:

```
13:06:45 Get:1 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-containers-image
1.0.0-29 [23.7 MB]
```
and
```
14:36:17 Get:1 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-containers-image
1.1.0-30 [33.7 MB]
```

OK, so the .img file seems to have grown. Now, if we grab the relevant .img files from:
https://github.com/kata-containers/runtime/releases/download/1.0.0/kata-containers.img
(warning, big download - not compressed)
and
https://build.opensuse.org/package/binary/download/home:katacontainers:release/kata-containers-image/xUbuntu_16.04/x86_64/kata-containers-image_1.1.0.orig.tar.gz

and then have a look inside them with something like:
```sh
sudo losetup -Pf kata-containers.img
sudo mount /dev/loop0p1 /mnt
sudo ls -laR /mnt
sudo du -sh /mnt/*
```

and dig around a bit - it seems that the 1.1.0 image is not stripped. To pick one example, the `/usr/lib/systemd` .so file:

For 1.0.0:
```
[root@gwhaley systemd]# ls -la *.so
-rwxr-xr-x. 1 root root 2396504 Jan 13  2017 libsystemd-shared-238.so
[root@gwhaley systemd]# file *.so
libsystemd-shared-238.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV),
dynamically linked, BuildID[sha1]=f104c0c626ba5b2e634a01000d2a5a8a29fb9e28,
stripped

[root@gwhaley systemd]# size *.so
   text	   data	    bss	    dec	    hex	filename
1817619	 574152	   7200	2398971	 249afb	libsystemd-shared-238.so
```

and for 1.1.1:
```
[root@gwhaley systemd]# ls -la *.so
-rwxr-xr-x. 1 root root 10224736 Jan 13  2017 libsystemd-shared-238.so
[root@gwhaley systemd]# file *.so
libsystemd-shared-238.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV),
dynamically linked, BuildID[sha1]=98c2f0cd18805c2298f85f6729d5733794584e14,
with debug_info, not stripped

[root@gwhaley systemd]# size *.so
   text	   data	    bss	    dec	    hex	filename
1817619	 574152	   7200	2398971	 249afb	libsystemd-shared-238.so
```

and for ref, if we look at the `df` of those two mounted images:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0p2    479M   66M  388M  15% /tmp/0
/dev/loop1p1    479M  117M  336M  26% /tmp/1
```

We can see the image filesystem is significantly more 'used'.

Now, over all, I don't know if this is an issue or not - but at least now we know where the space has gone I believe.
I guess the questions are:
- do we need debug symbols on the binaries in the .img file (I suspect not by default)
- Is this extra info in the .img file actually costing us memory footprint space?

For footprint space - I did measure it as PSS on the host side, and KSM will merge the pages.

I probably vote that we strip the .img by default.

/cc @jcvenegas @sboeuf @egernst

**Comment by sboeuf** [comment]
@grahamwhaley thanks for the detailed analysis here. It's good to understand what happened here :)
About what to do, I agree with you that we should strip the image because I believe we have a specific debug image where debug symbols can be enabled for this purpose.

**Comment by jcvenegas** [comment]
@grahamwhaley  thanks for create the issue, I still not take time to debug this. 

Those are good feedings
- agree to strip the image by default.
- I dont think we need debug symbols. 

 Today  os-builder is not used any more in the CI this probably caused we could not  detect this issue  earlier. So probably want to add some metrics in osbuilder.
