### ISSUE TITLE
kata-deploy: actions: should we delete the image/tags from the CI?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#957]
**Which feature do you think can be improved?**

When we trigger a kata-deploy actions build test, we
[push the image to the docker hub](https://github.com/kata-containers/packaging/blob/master/.github/workflows/kata-deploy-test.yaml#L43)
to [here](https://hub.docker.com/r/katadocker/kata-deploy-ci/tags)

I don't think we ever delete them. I'm guessing we probably should at the end of the test run, if for nothing else then to save consuming the planet?

**Comment by grahamwhaley** [comment]
@egernst

**Comment by grahamwhaley** [comment]
ping @egernst @chavafg

**Comment by egernst** [comment]
I think we need to just burn the planet, Graham.

AFAIU, there is not a way to delete images from Dockerhub.

**Comment by grahamwhaley** [comment]
:-( Only hint I can find is it might be [possibly through the REST API](https://stackoverflow.com/questions/44209644/how-do-i-delete-a-docker-image-from-docker-hub-via-command-line/44218747) - that just feels a little painful :-(

**Comment by ariel-adam** [comment]
@egernst Please decide if we should close this or not.
For our planet :-)

**Comment by ariel-adam** [comment]
We decided to close it for now.
