### ISSUE TITLE
snap: build snap images for ppc

### ISSUE THREAD

**Issue by devimc** [kata-containers/packaging#97]
snap build system requires `yq` to read packages versions but [`yq`](https://github.com/mikefarah/yq/releases/) is not available for ppc, an alternative to `yq` can be  `shyaml`.

**Comment by grahamwhaley** [comment]
`yq` is a golang prog - maybe you can use `go get; go install` instead if `shyaml` doesn't work out.

**Comment by nitkon** [comment]
FWIW: yq is available for ppc on Ubuntu
```
# uname -a
Linux llmtul01b 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:02 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
# yq --version
yq 2.6.0
```

**Comment by devimc** [comment]
@nitkon what package did you install ?

**Comment by devimc** [comment]
lol  yq for ppc64 is nor available as pre-release https://github.com/mikefarah/yq/releases/  :laughing:

**Comment by nitkon** [comment]
@devimc : Yes I am pushing for a release of yq on ppc64le. 
https://github.com/mikefarah/yq/issues/164

**Comment by devimc** [comment]
@nitkon great!
