### ISSUE TITLE
Disable virtio mmio on arm64 for kvm hypervisor  guest

### ISSUE THREAD

**Issue by justin-he** [kata-containers/packaging#985]
**Which feature do you think can be improved?**

Disable virtio mmio on arm64 for kvm hypervisor guest

**How can it be improved?**

Reduce arm64 vm boot time about 20-30ms

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?
yes

**Comment by ariel-adam** [comment]
@justin-he Is this still relevant?

**Comment by justin-he** [comment]
@c3d Okay, I will close it. Thanks for the reminder
