### ISSUE TITLE
k3s kata-deploy: Failed to restart containerd.service: Unit not found.

### ISSUE THREAD

**Issue by leolb-aphp** [kata-containers/packaging#996]
# Description of problem

I installed a k3s cluster version: `v1.17.4+k3s1`

I ran:

`$ kubectl apply -k github.com/kata-containers/packaging/kata-deploy/kata-deploy/overlays/k3s`

# Expected result

kata-containers installed on the cluster and ability to successfully run containers with its runtime class

# Actual result

**Failed to restart containerd.service: Unit not found.**

```
$ kubectl logs -n kube-system pod/kata-deploy-r76fj
time="2020-04-02T18:37:03Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/ca752b211ccbacb1b66df2ec0bc203a9511c0ec045ef5566b31c297958d46a3a"
copying kata artifacts onto host
Add Kata Containers as a supported runtime for containerd
Configuration exists for plugins.cri.containerd.runtimes.kata, overwriting
Configuration exists for plugins.cri.containerd.runtimes.kata.options, overwriting
Configuration exists for plugins.cri.containerd.runtimes.kata-fc, overwriting
Configuration exists for plugins.cri.containerd.runtimes.kata-fc.options, overwriting
warning: containerd-shim-kata-fc-v2 already exists
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-fc.toml /opt/kata/bin/containerd-shim-kata-v2 $@
Configuration exists for plugins.cri.containerd.runtimes.kata-qemu, overwriting
Configuration exists for plugins.cri.containerd.runtimes.kata-qemu.options, overwriting
warning: containerd-shim-kata-qemu-v2 already exists
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-qemu.toml /opt/kata/bin/containerd-shim-kata-v2 $@
Configuration exists for plugins.cri.containerd.runtimes.kata-qemu-virtiofs, overwriting
Configuration exists for plugins.cri.containerd.runtimes.kata-qemu-virtiofs.options, overwriting
warning: containerd-shim-kata-qemu-virtiofs-v2 already exists
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-qemu-virtiofs.toml /opt/kata/bin/containerd-shim-kata-v2 $@
Configuration exists for plugins.cri.containerd.runtimes.kata-clh, overwriting
Configuration exists for plugins.cri.containerd.runtimes.kata-clh.options, overwriting
warning: containerd-shim-kata-clh-v2 already exists
#!/bin/bash
KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-clh.toml /opt/kata/bin/containerd-shim-kata-v2 $@
Failed to restart containerd.service: Unit not found.
```

**Comment by devimc** [comment]
cc @egernst

**Comment by leolb-aphp** [comment]
@devimc @grahamwhaley 

Note that I wanted to debug and try solving the issue myself but it's unclear how you setup a development environment that does not depend on your CI setup which I do not have rights on so I figured I'll just pass it on upstream as it would be difficult making a pull request I can't test locally.

**Comment by jodh-intel** [comment]
@leolb-aphp - if you just want more log details, have you looked at enabling full debug output?:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug

/cc @mvincerx who might be interested in looking at our "documentation path" for users being able to self-diagnose issues.

**Comment by leolb-aphp** [comment]
> @leolb-aphp - if you just want more log details, have you looked at enabling full debug output?:
> 
> * https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug
> 
> /cc @mvincerx who might be interested in looking at our "documentation path" for users being able to self-diagnose issues.

I think that allows me to debug kata containers itself but not the installer script. I did not find anything that could allow a debug mode to be enabled in `kata-deploy.sh`.

I wanted to simply list the list of services because I'm suspecting maybe `containerd.service` doesnt exist, or it's config is invalid after `kata-deploy.sh` modified it somehow?

**Comment by devimc** [comment]
@leolb-aphp 

> But it seems that it always takes the script from a Docker image of your own?

yes, I think so, but I think you can modify the image (create a container, modify the script and save the container) and commit the change locally, right?

**Comment by grahamwhaley** [comment]
Last time I debugged the kata-deploy script, I ran up the daemonset, watched it fail, and then `kubectl exec bash` into the 'dead' node deployment container (you can find it in the system namespace), undid some of the damage by hand, edited the script (down in `/opt/kata/*`, and then re-ran it by hand directly on the node. It's not ideal, but it is workable.

If you have the ability to load a container image locally to your cluster, then you can rebuild your own local image and enable `set -x` etc. for debug, like @devimc suggests.

Also, there was a suggestion to add a debug mode to kata deploy over on https://github.com/kata-containers/packaging/issues/629 - I thought it was a good idea. We could pick that up again...

**Comment by mvincerx** [comment]
@jodh-intel. Thanks for the mention. I'll add this issue to my new project board -- forthcoming.

**Comment by wilsonianb** [comment]
I'm able to reproduce the issue and am looking into it.

FWIW, when I was working on adding k3s support, I would push my work in progress kata-deploy image to my personal dockerhub account and then test with that image in a k3s cluster.

**Comment by grahamwhaley** [comment]
I believe you can run a registry *inside* your own cluster - but, I've not been brave enough to try it yet.... https://blog.container-solutions.com/installing-a-registry-on-kubernetes-quickstart
So far, managed to work around it - or, use a minikube, where you can push images to its image cache directly from your host ;-) I have done that before.... and kata-deploy does work with minikube - https://github.com/kata-containers/documentation/blob/master/install/minikube-installation-guide.md
I have recently tried both cri-o and containerd minikubes with kata-deploy.
